/*
 * Copyright (c) 2025 Renesas Electronics Corporation
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include <zephyr/logging/log.h>
#include <zephyr/kernel.h>
#include <zephyr/toolchain.h>
#include "erpc_wifi.h"
#include "erpc_wifi_transport.h"
#include "erpc_wifi_cmd.h"
#include "erpc_wifi_cmd_process_handlers.h"
/* PMGR DPM job ids used by RA6W1 socket shim */
#ifndef ERPC_PMGR_JOB_ID_SEND
#define ERPC_PMGR_JOB_ID_SEND (1U)
#endif
#ifndef ERPC_PMGR_JOB_ID_RECV
#define ERPC_PMGR_JOB_ID_RECV (2U)
#endif

LOG_MODULE_REGISTER(erpc_wifi_socket_offload, CONFIG_WIFI_LOG_LEVEL);

void erpc_wifi_lock(void);
void erpc_wifi_unlock(void);
uint32_t get_socket_events(int32_t fd);
extern bool erpc_wifi_ps_is_enabled(void);
extern bool erpc_wifi_ps_begin_autonomous_wakeup(void);
extern void erpc_wifi_ps_finish_autonomous_wakeup(void);

extern void erpc_wifi_gpio_trigger_wakeup(void);


static atomic_t g_erpc_tx_blocked;
static atomic_t g_erpc_tx_block_timeout_ms;

/*
 * A GPIO wake generated by erpc_wifi_ensure_awake_tx() is HOST-initiated.
 *
 * The SRDY rising edge caused by that wake must not be consumed by the
 * autonomous socket-event path.  Without this ownership marker the poll
 * task can race the TX wake path, misclassify a FAST wake as autonomous,
 * issue GET_SOCKET_EVT, and steal/perturb the SRDY handshake that the TX
 * caller is waiting for.
 */
static atomic_t g_host_wake_inflight;

static K_MUTEX_DEFINE(g_active_tcp_job_mutex);
static uint32_t g_active_tcp_recv_port = 0;

void erpc_wifi_socket_invalidate_active_job_cache(void)
{
	k_mutex_lock(&g_active_tcp_job_mutex, K_FOREVER);
	g_active_tcp_recv_port = 0;
	k_mutex_unlock(&g_active_tcp_job_mutex);
}
void erpc_wifi_socket_tx_block_set(bool enable, uint32_t timeout_ms)
{
	atomic_set(&g_erpc_tx_blocked, enable ? 1 : 0);
	atomic_set(&g_erpc_tx_block_timeout_ms, (atomic_val_t)timeout_ms);
}

extern int32_t ra6w1_pmgr_dpm_is_wakeup(void);
extern int32_t ra6w1_pmgr_dpm_is_enabled(void);
extern int32_t ra6w1_pmgr_dpm_wakeup_done(uint32_t job_id);
extern int32_t ra6w1_pmgr_dpm_rcv_ready_set(uint32_t job_id);
extern int32_t ra6w1_pmgr_dpm_job_name_set(uint32_t job_id, const char *job_name);
extern int32_t ra6w1_pmgr_add_sleep_constraint(uint32_t constraint);
extern int32_t ra6w1_pmgr_remove_sleep_constraint(uint32_t constraint);
extern int erpc_wifi_transport_slave_ready(void);
extern struct erpc_wifi_data erpc_wifi_driver_data;

/* Forward declaration for pmgr_ram_hold used in erpc_wifi_ensure_awake_tx */
static inline int pmgr_ram_hold(void);

/*
 * erpc_wifi_ensure_awake_rx - Used after an RX/socket event is known.
 * May re-pulse WAKE if SRDY was consumed by the preceding
 * event-query transaction.
 *
 * Must not be used by idle background polling to wake RA.
 */
static int erpc_wifi_ensure_awake_rx(uint32_t job_id, bool *ram_held)
{
	ARG_UNUSED(job_id);

	__ASSERT(!*ram_held, "ensure_awake_rx called while POWER_RAM already held");
	*ram_held = false;

	/*
	 * Wait until autonomous wake has been claimed by the
	 * host PS state machine.
	 */
	erpc_wifi_ps_wait_awake_rx();

	if (!erpc_wifi_ps_is_enabled()) {
		return 0;
	}

	/*
	 * SRDY may have fallen after GET_SOCKET_EVT although
	 * RA is still awake. Reassert it for the next host
	 * initiated eRPC transaction.
	 */
	if (!erpc_wifi_transport_slave_ready()) {
		erpc_wifi_gpio_wakeup_pulse_fast();

		int64_t deadline = k_uptime_get() + 300;

		while (!erpc_wifi_transport_slave_ready() &&
		       k_uptime_get() < deadline) {
			k_msleep(5);
		}

		if (!erpc_wifi_transport_slave_ready()) {
			LOG_WRN("RX wake: SRDY did not assert");
			return -EAGAIN;
		}
	}

	/*
	 * Every RX operation that later releases POWER_RAM
	 * must own its own POWER_RAM reference.
	 */
	int hold_rc = pmgr_ram_hold();

	if (hold_rc < 0) {
		LOG_WRN("RX POWER_RAM hold failed: %d", hold_rc);
		return hold_rc;
	}

	*ram_held = true;

	return 0;
}

static int erpc_wifi_ensure_awake_tx(uint32_t job_id, bool *ram_held)
{
	__ASSERT(!*ram_held, "ensure_awake_tx called while POWER_RAM already held");
	*ram_held = false;

	erpc_wifi_ps_wait_awake_tx();

	erpc_wifi_ps_cancel_sleep_work();

	if (atomic_get(&g_erpc_tx_blocked) == 0) {
		if (!erpc_wifi_ps_is_enabled() || erpc_wifi_transport_slave_ready() == 1) {
			if (erpc_wifi_ps_is_enabled()) {
				if (erpc_wifi_transport_slave_ready() == 1) {
					int ps_rc = erpc_wifi_ps_hold_awake("tx-awake");
					if (ps_rc != 0) {
						/*
						 * wait_awake_tx() may have reserved WAKING_UP for this
						 * operation.  Never return with that transition stranded.
						 */
						erpc_wifi_ps_wake_failed();
						return ps_rc;
					}
				}
				/* Ensure POWER_RAM hold is acquired to protect this socket operation */
				int hold_rc = pmgr_ram_hold();
				if (hold_rc < 0) {
					LOG_WRN("TX POWER_RAM hold failed: %d", hold_rc);
					erpc_wifi_ps_wake_failed();
					return hold_rc;
				}
				*ram_held = true;
			}
			LOG_DBG("TX wake skipped (tx_blocked=0, job=%u)", job_id);
			erpc_wifi_ps_reset_state_awake();
			return 0;
		}

		LOG_INF("TX wake override (job=%u): tx_blocked=0 but slave-ready=0 while PS enabled",
			job_id);
	}

	int64_t start = k_uptime_get();
	uint32_t tmo = CONFIG_WIFI_ERPC_WAKE_TIMEOUT_MS;
	int64_t last_pulse = start;

	/*
	 * From this point until the wake is either completed or abandoned,
	 * this host TX path owns SRDY wake classification.  The GPIO rising
	 * edge is a response to OUR wake pulse, not proof of autonomous UC RX.
	 */
	atomic_set(&g_host_wake_inflight, 1);

	/* Proactively pulse Wakeup GPIO fast */
	erpc_wifi_gpio_wakeup_pulse_fast();

	for (;;) {
		if (tmo > 0U && (k_uptime_get() - start) >= (int64_t)tmo) {
			LOG_WRN("TX wake timeout job=%u tmo=%u", job_id, tmo);

			/*
			 * Drop wake ownership BEFORE publishing the failed host state.
			 * No autonomous event is manufactured from the host wake pulse;
			 * a later genuine network edge will generate its own IRQ.
			 */
			atomic_set(&g_host_wake_inflight, 0);
			erpc_wifi_ps_wake_failed();
			return -EAGAIN;
		}

		int sr = erpc_wifi_transport_slave_ready();

		/* SPI slave-ready going active means RA side is up enough for eRPC traffic. */
		if (sr == 1) {
			int stable = 0;

			for (int i = 0; i < 3; i++) {
				if (erpc_wifi_transport_slave_ready() == 1) {
					stable++;
				}
				k_msleep(3);
			}

			if (stable < 3) {
				k_msleep(5);
				continue;
			}
			/*
			 * FULL DPM wake requires time for RA6W1 transport,
			 * RTM socket restore and internal tasks to settle.
			 *
			 * This delay is only on a real DPM wake path.
			 */
			k_msleep(150);

			/* Re-verify SRDY after wake settle. */
			if (!erpc_wifi_transport_slave_ready()) {
				k_msleep(50);
				continue;
			}

			if (pmgr_ram_hold() < 0) {
				k_msleep(50);
				continue;
			}
			*ram_held = true;
			
			int ps_rc = erpc_wifi_ps_hold_awake("tx-awake");
			if (ps_rc != 0) {
				int rel_rc = erpc_wifi_pmgr_ram_release(0);
				if (rel_rc == 0) {
					*ram_held = false;
				}
				atomic_set(&g_host_wake_inflight, 0);
				erpc_wifi_ps_wake_failed();
				return ps_rc;
			}

			/* Tell PMGR this module has pending I/O work only after wake is visible. */
			{
				erpc_wifi_pmgr_job_t job_msg = { .job_id = job_id };
				int32_t rc = (int32_t)erpc_wifi_send_cmd(ERPC_WIFI_PMGR_DPM_RCV_READY_SET_CMD,
													 &job_msg, sizeof(job_msg), -1);
				if (rc < 0) {
					LOG_WRN("TX wake prep failed: rcv_ready_set rc=%d", rc);
					/* Balancing: release only POWER_RAM constraint, set ram_held = false, and retry */
					if (*ram_held) {
						int rel_rc = erpc_wifi_pmgr_ram_release(0);
						if (rel_rc != 0) {
							LOG_ERR("POWER_RAM release failed during wake retry: %d", rel_rc);
							atomic_set(&g_host_wake_inflight, 0);
							erpc_wifi_ps_wake_failed();
							return rel_rc;
						}
						*ram_held = false;
					}
					k_msleep(50);
					continue;
				}
			}
			erpc_wifi_ps_reset_state_awake();

			/*
			 * Publish AWAKE before releasing host-wake ownership.  If a pending
			 * socket IRQ is processed after this point it cannot be mistaken for
			 * an ASLEEP->autonomous wake transition.
			 */
			atomic_set(&g_host_wake_inflight, 0);
			return 0;
		}

		/* Some boards require repeated wake pulses while RA6W1 is in DPM. */
		if ((k_uptime_get() - last_pulse) > 300) {
			erpc_wifi_gpio_wakeup_pulse_fast();
			last_pulse = k_uptime_get();
		}

		k_msleep(10);
	}
}
extern void erpc_wifi_lock(void);
extern void erpc_wifi_unlock(void);

#ifndef PMGR_CONSTRAINT_SLEEP_PROHIBITED
#define PMGR_CONSTRAINT_SLEEP_PROHIBITED (1U << 0)
#endif
#ifndef PMGR_CONSTRAINT_POWER_RAM
#define PMGR_CONSTRAINT_POWER_RAM (1U << 2)
#endif

static int pmgr_dpm_cached_enabled(void)
{
	static int cached = -1;

	if (cached >= 0) {
		return cached;
	}

	int32_t en = (int32_t)erpc_wifi_send_cmd(ERPC_WIFI_PMGR_DPM_IS_ENABLED_CMD, NULL, 0, -1);
	cached = (en == 1) ? 1 : 0;
	return cached;
}

static inline int pmgr_ram_hold(void)
{
	if (pmgr_dpm_cached_enabled()) {
		int32_t rc = -1;
		for (int i = 0; i < 5; i++) {
			erpc_wifi_pmgr_constraint_t cstr = { .constraint = PMGR_CONSTRAINT_POWER_RAM };
			rc = (int32_t)erpc_wifi_send_cmd(ERPC_WIFI_PMGR_ADD_SLEEP_CONSTRAINT_CMD,
											  &cstr, sizeof(cstr), -1);
			if (rc >= 0) {
				break;
			}
			/* Transient SPI CRC error (err 8) is common on the first frame after DPM wake due to
			 * hardware synchronization. Retry. */
			k_msleep(10);
		}
		if (rc < 0) {
			LOG_ERR("pmgr_ram_hold failed: %d", rc);
			return rc;
		}
	}

	return 0;
}

int erpc_wifi_pmgr_ram_release(uint32_t job_id)
{
	if (pmgr_dpm_cached_enabled()) {
		int32_t rc = -1;
		for (int i = 0; i < 5; i++) {
			erpc_wifi_pmgr_constraint_t cstr = { .constraint = PMGR_CONSTRAINT_POWER_RAM };
			rc = (int32_t)erpc_wifi_send_cmd(ERPC_WIFI_PMGR_REMOVE_SLEEP_CONSTRAINT_CMD,
											  &cstr, sizeof(cstr), -1);
			if (rc >= 0) {
				break;
			}
			k_msleep(10);
		}
		if (rc < 0) {
			LOG_ERR("pmgr_ram_release failed: %d", rc);
			return rc;
		}
		if (job_id != 0) {
			erpc_wifi_pmgr_job_t job_msg = { .job_id = job_id };
			(void)erpc_wifi_send_cmd(ERPC_WIFI_PMGR_DPM_WAKEUP_DONE_CMD,
								   &job_msg, sizeof(job_msg), -1);
		}
	}
	return 0;
}

/*
 * erpc_wifi_wake_for_tx - exported wrapper for callers outside this file
 * (e.g. DNS offload) that need to perform a host-initiated eRPC operation
 * while the RA6W1 may be in DPM sleep.
 */
int erpc_wifi_wake_for_tx(void)
{
	bool ram_held = false;
	int ret = erpc_wifi_ensure_awake_tx(ERPC_PMGR_JOB_ID_SEND, &ram_held);
	if (ret < 0) {
		if (ram_held) {
			(void)erpc_wifi_pmgr_ram_release(ERPC_PMGR_JOB_ID_SEND);
		}
	}
	return ret;
}

/*
 * Ownership-safe variant for non-socket callers such as DNS.
 * On success, *ram_held tells the caller whether it owns a POWER_RAM
 * reference that must be released exactly once after the eRPC sequence.
 */
int erpc_wifi_wake_for_tx_acquire(bool *ram_held)
{
	if (ram_held == NULL) {
		return -EINVAL;
	}

	*ram_held = false;

	int ret =
		erpc_wifi_ensure_awake_tx(
			ERPC_PMGR_JOB_ID_SEND,
			ram_held);

	if (ret < 0 && *ram_held) {
		(void)erpc_wifi_pmgr_ram_release(
			ERPC_PMGR_JOB_ID_SEND);
		*ram_held = false;
	}

	return ret;
}

#include <zephyr/sys/atomic.h>
#include <zephyr/device.h>
#include <string.h>
#include <stdlib.h>
#include <errno.h>
#include <zephyr/posix/fcntl.h>

#include <zephyr/net/net_pkt.h>
#include <zephyr/net/net_if.h>
#include <zephyr/net/net_offload.h>
#include <zephyr/net/socket_offload.h>

#include "sockets_internal.h"

#include "c_wifi_host_to_ra_client.h"
#include "c_wifi_ra_to_host_client.h"

#include <zephyr/net/socket.h>

#define ERPC_WIFI_AF_INET  2
#define ERPC_WIFI_AF_INET6 10

#define ERPC_WIFI_SOL_SOCKET 0xfff

#define ERPC_WIFI_SO_DEBUG        0x0001
#define ERPC_WIFI_SO_REUSEADDR    0x0004
#define ERPC_WIFI_SO_TYPE         0x1008
#define ERPC_WIFI_SO_ERROR        0x1007
#define ERPC_WIFI_SO_DONTROUTE    0x0010
#define ERPC_WIFI_SO_BROADCAST    0x0020
#define ERPC_WIFI_SO_SNDBUF       0x1001
#define ERPC_WIFI_SO_RCVBUF       0x1002
#define ERPC_WIFI_SO_KEEPALIVE    0x0008
#define ERPC_WIFI_SO_OOBINLINE    0x0100
#define ERPC_WIFI_SO_LINGER       0x0080
#define ERPC_WIFI_SO_REUSEPORT    0x0200
#define ERPC_WIFI_SO_RCVLOWAT     0x1004
#define ERPC_WIFI_SO_SNDLOWAT     0x1003
#define ERPC_WIFI_SO_RCVTIMEO     0x1006
#define ERPC_WIFI_SO_SNDTIMEO     0x1005
#define ERPC_WIFI_SO_BINDTODEVICE 0x100b
#define ERPC_WIFI_SO_ACCEPTCONN   0x0002

#define ERPC_WIFI_MAX_SOCKETS 4

static struct net_if *net_iface;

static struct erpc_wifi_socket *find_socket_by_fd(int zfd);

static int erpc_wifi_poll_hup_on_iface_down(struct zvfs_pollfd *fds, int nfds)
{
	int ret = 0;

	if (net_if_is_up(net_iface)) {
		return 0;
	}

	for (int i = 0; i < nfds; i++) {
		if (find_socket_by_fd(fds[i].fd)) {
			fds[i].revents = ZSOCK_POLLHUP;
			ret++;
		}
	}

	return ret;
}
// Event flags that match what you'll return
#define SOCKET_EVENT_RX    0x01 // POLLIN - Data available to read
#define SOCKET_EVENT_TX    0x02 // POLLOUT - Ready to write
#define SOCKET_EVENT_ERR   0x04 // POLLERR - Error condition
#define SOCKET_EVENT_CLOSE 0x08 // POLLHUP - Connection closed

#if 0
struct erpc_wifi_socket {
    int fd;          // remote FD
    int zfd;          // Zephyr FD
    bool in_use;

    bool waiting;
    struct k_poll_signal poll_signal;  // Add this
    short poll_events;                 // Events poll is waiting for
    short triggered_events;            // Events that occurred
    int type;        // POSIX socket type (e.g. SOCK_STREAM)
    uint16_t bound_port;   // Local port from bind() (host order)
    bool tcp_dpm_filter_set; // true if TCP DPM wake filter installed

};
#endif
#include <zephyr/spinlock.h>

struct erpc_wifi_socket {
	int zfd; // Zephyr FD
	int fd;  // remote FD
	int family;
	int type;
	int protocol;
	bool in_use;

	bool waiting;
	struct k_poll_signal poll_signal; // Add this
	//	short poll_events;                 // Events poll is waiting for
	short triggered_events; // Events that occurred
	/* poll bookkeeping */
	struct zsock_pollfd *pollfd; /* pointer stored in POLL_PREPARE */
	uint16_t poll_events;        /* events user requested in pollfd->events */
	uint16_t pending_revents;    /* events actually occurred, to be returned in POLL_UPDATE */

	struct k_sem read_sem;
	struct k_fifo fifo;
	
	struct k_work socket_connect_work;
	struct ra_erpc_sockaddr *addr_erpc_wifi;

	// erpc_service_t service;

	erpc_server_t server;
	erpc_client_t client;

	char addr_str[NET_IPV6_ADDR_LEN]; /* Supports both IPv4 and IPv6 */
	int port;

	struct k_mutex *lock;    /* for ZFD_IOCTL_SET_LOCK */
	bool connect_pending;
	bool connected;
	int socket_error;
	uint32_t flags;          /* O_NONBLOCK etc */
	uint16_t bound_port;     // Local port from bind() (host order)
	bool tcp_dpm_filter_set; // true if TCP DPM wake filter installed
	uint32_t recv_timeout_ms;
	uint32_t send_timeout_ms;
	bool closing;            // true if close() is in progress
	struct k_spinlock state_lock;

	struct sockaddr addr;
	socklen_t addrlen;
};

static struct erpc_wifi_socket sockets[ERPC_WIFI_MAX_SOCKETS];

K_THREAD_STACK_DEFINE(erpc_wifi_socket_poll_stack, 8192);
static struct k_thread erpc_wifi_socket_poll_thread_data;
static k_tid_t erpc_wifi_socket_poll_tid;
struct k_sem poll_task_sem;
static atomic_t g_srdy_irq_pending;
static atomic_t g_socket_evt_query_inflight;
static atomic_t g_server_evt_query_inflight;
static atomic_t g_host_erpc_inflight;
static atomic_t g_srdy_deferred;

static struct k_work_delayable g_srdy_deferred_work;

static void erpc_wifi_srdy_deferred_work(struct k_work *work)
{
	ARG_UNUSED(work);

	/*
	 * During an explicit host GPIO wake, SRDY activity belongs to the host
	 * wake/eRPC handshake.  Do not turn that response into an autonomous
	 * socket wake after the eRPC completes.
	 */
	if (atomic_get(&g_host_wake_inflight) != 0) {
		atomic_set(&g_srdy_deferred, 0);
		return;
	}

	/* Another host eRPC started. Check after it completes. */
	if (atomic_get(&g_host_erpc_inflight) != 0) {
		k_work_reschedule(&g_srdy_deferred_work, K_MSEC(5));
		return;
	}

	/*
	 * Never carry the SLEEP_PROHIBITED REMOVE response
	 * across the sleep-entry guard.
	 */
	if (erpc_wifi_ps_is_enabled() &&
	    erpc_wifi_ps_wait_for_srdy_low_get()) {

		atomic_set(&g_srdy_deferred, 0);
		return;
	}

	if (!atomic_cas(&g_srdy_deferred, 1, 0)) {
		return;
	}

	if (erpc_wifi_transport_slave_ready()) {
		atomic_set(&g_srdy_irq_pending, 1);
	}

	/*
	 * Even if SRDY already fell, do one socket-event recovery pass.
	 * This is NOT treated as autonomous wake unless SRDY is actually high.
	 */
	k_sem_give(&poll_task_sem);
}

void erpc_wifi_offload_server_evt_query_begin(void)
{
	atomic_set(&g_server_evt_query_inflight, 1);
}

void erpc_wifi_offload_server_evt_query_end(void)
{
	atomic_set(&g_server_evt_query_inflight, 0);
}

void erpc_wifi_offload_host_erpc_begin(void)
{
	atomic_set(&g_host_erpc_inflight, 1);
}

void erpc_wifi_offload_host_erpc_end(void)
{
	atomic_set(&g_host_erpc_inflight, 0);

	if (atomic_get(&g_srdy_deferred) != 0) {
		k_work_reschedule(&g_srdy_deferred_work, K_MSEC(5));
	}
}
static void erpc_wifi_socket_poll_task(void *arg1, void *arg2, void *arg3)
{
	ARG_UNUSED(arg1);
	ARG_UNUSED(arg2);
	ARG_UNUSED(arg3);
	int64_t last_not_ready_log = 0;
	int last_srdy_level = erpc_wifi_transport_slave_ready();

	while (1) {
		/*
		 * Customer-stable servicing semantics:
		 *   - an active socket waiter is revisited every 200 ms;
		 *   - a filtered DPM TCP socket gets a 500 ms fallback pass.
		 *
		 * The timeout only services sockets while the module is already awake.
		 * It does NOT wake a genuinely sleeping RA6W1.
		 */
		bool waiter_polling_needed = false;
		bool dpm_polling_needed = false;

		for (int i = 0; i < ERPC_WIFI_MAX_SOCKETS; i++) {
			if (!sockets[i].in_use) {
				continue;
			}

			if (sockets[i].waiting || sockets[i].connect_pending) {
				waiter_polling_needed = true;
			}

			if (erpc_wifi_ps_is_enabled() &&
			    sockets[i].type == SOCK_STREAM &&
			    sockets[i].tcp_dpm_filter_set) {
				dpm_polling_needed = true;
			}
		}

		k_timeout_t wait_timeout =
			waiter_polling_needed ? K_MSEC(200) :
			(dpm_polling_needed ? K_MSEC(500) : K_FOREVER);

		int wait_rc = k_sem_take(&poll_task_sem, wait_timeout);
		bool fallback_timeout = (wait_rc != 0);
		bool dpm_timeout = fallback_timeout && !waiter_polling_needed && dpm_polling_needed;

		/*
		 * An explicit host TX wake owns SRDY until ensure_awake_tx() has
		 * completed.  Do not consume/classify its rising edge here.
		 * Also absorb the sampled level so the host-generated rise cannot
		 * later be reconstructed as a missed autonomous edge.
		 */
		if (atomic_get(&g_host_wake_inflight) != 0) {
			last_srdy_level = erpc_wifi_transport_slave_ready();
			k_msleep(5);
			continue;
		}

		int srdy_level = erpc_wifi_transport_slave_ready();
		bool sampled_srdy_rise = (last_srdy_level == 0 && srdy_level == 1);
		last_srdy_level = srdy_level;

		/*
		 * Normally the ISR supplies the edge.  The sampled 0->1 transition is
		 * a constrained recovery for a genuinely missed/coalesced IRQ; unlike
		 * a static-SRDY-HIGH fallback it still requires an observed transition.
		 */
		bool srdy_irq = atomic_cas(&g_srdy_irq_pending, 1, 0) || sampled_srdy_rise;

		/* Skip polling if WiFi interface is not connected */
		if (erpc_wifi_driver_data.state != WIFI_STATE_COMPLETED) {
			k_msleep(100);
			continue;
		}

#if defined(CONFIG_NET_IPV4)
		if (erpc_wifi_ps_is_enabled() && !erpc_wifi_driver_data.ipv4_assigned) {
			k_msleep(50);
			continue;
		}
#endif

		bool ps_enabled = erpc_wifi_ps_is_enabled();
		bool module_asleep =
			ps_enabled &&
			erpc_wifi_ps_is_module_asleep();

		if (erpc_wifi_ps_is_enabled() && erpc_wifi_ps_wait_for_srdy_low_get()) {
			/*
			 * IMPORTANT:
			 * Ignore SRDY edges during the sleep-entry quiet window.
			 *
			 * SLEEP_PROHIBITED REMOVE itself generates normal
			 * SPI/eRPC SRDY activity. That edge must NOT later be
			 * interpreted as an autonomous DPM/socket wake.
			 */
			k_msleep(20);
			continue;
		}

		/*
		 * Release candidate: autonomous DPM wake qualification is edge based.
		 * A host-generated FAST wake is suppressed by g_host_wake_inflight;
		 * a real/deferred asynchronous SRDY edge remains the UC event source.
		 */
		bool autonomous_pass =
			module_asleep &&
			srdy_irq;

		bool autonomous_started = false;

		if (autonomous_pass) {
			/*
			 * Let the RA6W1 finish UC wake + RTM socket restore first.
			 * Do not send any PMGR command during this interval.
			 */
			k_msleep(150);

			if (!erpc_wifi_transport_slave_ready()) {
				LOG_DBG("Ignoring stale autonomous SRDY");
				continue;
			}

			/*
			 * Freeze normal host eRPC producers in WAKING_UP, but do not
			 * claim SLEEP_PROHIBITED yet.  GET_SOCKET_EVT must be the first
			 * host transaction after an RA-originated UC wake.
			 */
			autonomous_started =
				erpc_wifi_ps_begin_autonomous_wakeup();

			if (!autonomous_started) {
				/*
				 * Another host wake path won the race.  Let that path finish;
				 * a waiting socket will be revisited by the normal poll pass.
				 */
				continue;
			}
		}

		for (int i = 0; i < ERPC_WIFI_MAX_SOCKETS; i++) {
			struct erpc_wifi_socket *sock = &sockets[i];

			if (!sock->in_use) {
				continue;
			}

			bool waiter_probe = sock->waiting || sock->connect_pending;

			/*
			 * One real autonomous wake may belong to ANY filtered
			 * TCP socket. Query all of them once.
			 */
			bool dpm_event_probe =
				autonomous_pass &&
				sock->type == SOCK_STREAM &&
				(sock->tcp_dpm_filter_set || sock->connect_pending);

			/*
			 * Restore the customer-stable missed-edge fallback: on the 500 ms
			 * servicing timeout, re-query a filtered TCP socket if the host PS
			 * state already says RA6W1 is awake.  Never turn this timeout into a
			 * wake request while the module is genuinely asleep.
			 */
			bool filtered_tcp =
				sock->type == SOCK_STREAM &&
				(sock->tcp_dpm_filter_set || sock->connect_pending);

			/*
			 * Match the customer-stable scanner more closely:
			 * - while PS is disabled, a 200 ms waiter tick services only waiters;
			 *   it must not scan unrelated filtered sockets;
			 * - while PS is enabled and RA is already awake, a real SRDY IRQ may
			 *   query all filtered TCP sockets; the periodic filtered-socket fallback
			 *   remains 500 ms and does not collapse to 200 ms because another socket
			 *   happens to have an active waiter.
			 */
			bool awake_irq_probe =
				ps_enabled &&
				srdy_irq &&
				!module_asleep &&
				filtered_tcp;

			bool awake_fallback_probe =
				ps_enabled &&
				dpm_timeout &&
				!module_asleep &&
				filtered_tcp;

			if (!waiter_probe && !dpm_event_probe &&
			    !awake_irq_probe && !awake_fallback_probe) {
				continue;
			}

			/*
			 * Never let ensure_awake_rx() wait forever for an AWAKE
			 * transition that the poll task itself has not established.
			 */
			if (erpc_wifi_ps_is_enabled() &&
			    !autonomous_started &&
			    !erpc_wifi_ps_is_module_awake()) {
				continue;
			}

			int srdy = erpc_wifi_transport_slave_ready();

			if (!srdy && !dpm_event_probe) {
				bool pollout_probe =
					waiter_probe &&
					((sock->poll_events & ZVFS_POLLOUT) || sock->connect_pending);

				bool irq_wait_probe =
					waiter_probe && srdy_irq;

				/*
				 * Customer-stable code services an awake waiter even when SRDY has
				 * already fallen after the previous eRPC. ensure_awake_rx() below
				 * reasserts SRDY for the query. This is the missing 200 ms retry
				 * behavior needed by TLS/MQTT waiters.
				 */
				bool awake_waiter_probe = waiter_probe && !module_asleep;

				if (!pollout_probe && !irq_wait_probe &&
				    !awake_waiter_probe && !awake_fallback_probe) {
					continue;
				}
			}

			/*
			 * IMPORTANT: GET_SOCKET_EVT is only an event inspection.  Do not
			 * acquire POWER_RAM for every 200/500 ms poll pass.  Doing so turns
			 * one MQTT/TLS waiter into a stream of PMGR ADD_SLEEP_CONSTRAINT
			 * commands and can starve real send/recv/socket-create traffic.
			 *
			 * This matches the customer-stable ownership model: if RA is already
			 * awake but SRDY has fallen after the previous SPI transaction, issue
			 * only a short host wake pulse to reassert SRDY.  Real recv/send paths
			 * still acquire/release POWER_RAM through ensure_awake_rx/tx().
			 *
			 * Autonomous RA-originated wake is already ready for its first
			 * GET_SOCKET_EVT and must not be host-pulsed here.
			 */
			if (!autonomous_started && ps_enabled) {
				if (!erpc_wifi_ps_is_module_awake()) {
					continue;
				}

				if (!erpc_wifi_transport_slave_ready()) {
					/* Own only this explicit poll re-pulse so its SRDY edge is not
					 * reconstructed as an autonomous wake.  If another host wake
					 * already owns the line, defer this poll pass. */
					if (!atomic_cas(&g_host_wake_inflight, 0, 1)) {
						continue;
					}

					erpc_wifi_gpio_wakeup_pulse_fast();

					int64_t deadline = k_uptime_get() + 300;
					while (!erpc_wifi_transport_slave_ready() &&
					       k_uptime_get() < deadline) {
						k_msleep(5);
					}

					bool ready = erpc_wifi_transport_slave_ready();
					atomic_set(&g_host_wake_inflight, 0);

					if (!ready) {
						continue;
					}

					/* Absorb our own sampled 0->1 level so the next loop cannot
					 * reinterpret the poll re-pulse as an autonomous SRDY edge. */
					last_srdy_level = 1;
				}
			}

			int ev_fd = sock->fd;

			atomic_set(&g_socket_evt_query_inflight, 1);

			uint32_t events =
				(uint32_t)erpc_wifi_send_cmd(
				EPRC_WIFI_GET_SOCKET_EVT_CMD,
				&ev_fd,
				sizeof(ev_fd), -1);

			atomic_set(&g_socket_evt_query_inflight, 0);

			if (events == UINT32_MAX) {
				LOG_DBG("poll get_socket_events failed fd=%d; deferring", sock->fd);
				continue;
			}

			bool notify_connected = false;
			bool notify_failed = false;
			int log_connected_fd = -1;
			int log_failed_fd = -1;

			k_spinlock_key_t key = k_spin_lock(&sock->state_lock);
			uint32_t all_events = events & (SOCKET_EVENT_RX | SOCKET_EVENT_TX | SOCKET_EVENT_ERR | SOCKET_EVENT_CLOSE);
			sock->triggered_events |= (short)all_events;

			if (sock->connect_pending) {
				if (events & SOCKET_EVENT_TX) {
					sock->connect_pending = false;
					sock->connected = true;
					sock->socket_error = 0;
					notify_connected = true;
					log_connected_fd = sock->fd;
				} else if (events & (SOCKET_EVENT_ERR | SOCKET_EVENT_CLOSE)) {
					sock->connect_pending = false;
					sock->connected = false;
					sock->socket_error = -1;
					notify_failed = true;
					log_failed_fd = sock->fd;
				}
			}

			uint32_t requested_mask = 0;
			if (sock->poll_events & ZVFS_POLLIN) {
				requested_mask |= SOCKET_EVENT_RX;
			}
			if (sock->poll_events & ZVFS_POLLOUT) {
				requested_mask |= SOCKET_EVENT_TX;
			}
			requested_mask |= SOCKET_EVENT_ERR | SOCKET_EVENT_CLOSE;

			uint32_t ready = sock->triggered_events & requested_mask;
			bool do_signal = false;

			if (sock->waiting && ready != 0) {
				sock->waiting = false;
				do_signal = true;
			}
			k_spin_unlock(&sock->state_lock, key);

			if (notify_connected) {
				erpc_wifi_ps_notify_socket_connected();
				LOG_DBG("Non-blocking connect completed for fd %d", log_connected_fd);
			}
			if (notify_failed) {
				erpc_wifi_ps_notify_socket_connect_failed();
				LOG_WRN("Non-blocking connect failed for fd %d", log_failed_fd);
			}

			if (do_signal) {
				k_poll_signal_raise(&sock->poll_signal, (int)ready);
			}
		}

		/*
		 * Release application/event-monitor waiters only after every restored
		 * DPM TCP socket has had one GET_SOCKET_EVT query.
		 */
		if (autonomous_started) {
			erpc_wifi_ps_finish_autonomous_wakeup();
		}
	}
}

static void ensure_poll_task_started(void)
{
	if (erpc_wifi_socket_poll_tid != NULL) {
		return;
	}

	erpc_wifi_socket_poll_tid = k_thread_create(
		&erpc_wifi_socket_poll_thread_data, erpc_wifi_socket_poll_stack,
		K_THREAD_STACK_SIZEOF(erpc_wifi_socket_poll_stack), erpc_wifi_socket_poll_task,
		NULL, NULL, NULL, K_PRIO_PREEMPT(7), 0, K_NO_WAIT);
	k_thread_name_set(erpc_wifi_socket_poll_tid, "erpc_socket_poll");
}
static const struct socket_op_vtable erpc_wifi_socket_fd_op_vtable;

static int erpc_wifi_socket_level_from_posix(int level, int *level_erpc_wifi)
{
	switch (level) {
	case SOL_SOCKET:
		*level_erpc_wifi = ERPC_WIFI_SOL_SOCKET;
		break;
		case IPPROTO_TCP:
		*level_erpc_wifi = IPPROTO_TCP;
		break;
	default:
		return -EAFNOSUPPORT;
		break;
	}

	return 0;
}

static int erpc_wifi_socket_option_from_posix(int level, int optname, int *optname_erpc_wifi)
{
	if (level == IPPROTO_TCP) {
		*optname_erpc_wifi = optname;
		return 0;
	}
	
	switch (optname) {
	case SO_DEBUG:
		*optname_erpc_wifi = ERPC_WIFI_SO_DEBUG;
		break;
	case SO_REUSEADDR:
		*optname_erpc_wifi = ERPC_WIFI_SO_REUSEADDR;
		break;
	case SO_TYPE:
		*optname_erpc_wifi = ERPC_WIFI_SO_TYPE;
		break;
	case SO_ERROR:
		*optname_erpc_wifi = ERPC_WIFI_SO_ERROR;
		break;
	case SO_DONTROUTE:
		*optname_erpc_wifi = ERPC_WIFI_SO_DONTROUTE;
		break;
	case SO_BROADCAST:
		*optname_erpc_wifi = ERPC_WIFI_SO_BROADCAST;
		break;
	case SO_SNDBUF:
		*optname_erpc_wifi = ERPC_WIFI_SO_SNDBUF;
		break;
	case SO_RCVBUF:
		*optname_erpc_wifi = ERPC_WIFI_SO_RCVBUF;
		break;
	case SO_KEEPALIVE:
		*optname_erpc_wifi = ERPC_WIFI_SO_KEEPALIVE;
		break;
	case SO_OOBINLINE:
		*optname_erpc_wifi = ERPC_WIFI_SO_OOBINLINE;
		break;
	case SO_LINGER:
		*optname_erpc_wifi = ERPC_WIFI_SO_LINGER;
		break;
	case SO_REUSEPORT:
		*optname_erpc_wifi = ERPC_WIFI_SO_REUSEPORT;
		break;
	case SO_RCVLOWAT:
		*optname_erpc_wifi = ERPC_WIFI_SO_RCVLOWAT;
		break;
	case SO_SNDLOWAT:
		*optname_erpc_wifi = ERPC_WIFI_SO_SNDLOWAT;
		break;
	case SO_RCVTIMEO:
		*optname_erpc_wifi = ERPC_WIFI_SO_RCVTIMEO;
		break;
	case SO_SNDTIMEO:
		*optname_erpc_wifi = ERPC_WIFI_SO_SNDTIMEO;
		break;
	case SO_BINDTODEVICE:
		*optname_erpc_wifi = ERPC_WIFI_SO_BINDTODEVICE;
		break;
	case SO_ACCEPTCONN:
		*optname_erpc_wifi = ERPC_WIFI_SO_ACCEPTCONN;
		break;
	default:
		return -EAFNOSUPPORT;
		break;
	}

	return 0;
}

static int erpc_wifi_socket_family_to_posix(uint8_t family_erpc_wifi, int *family)
{
	switch (family_erpc_wifi) {
	case ERPC_WIFI_AF_INET:
		*family = AF_INET;
		break;
	case ERPC_WIFI_AF_INET6:
		*family = AF_INET6;
		break;
	default:
		return -EAFNOSUPPORT;
		break;
	}

	return 0;
}

static int erpc_wifi_socket_family_from_posix(int family, uint8_t *family_erpc_wifi)
{
	switch (family) {
	case AF_INET:
		*family_erpc_wifi = ERPC_WIFI_AF_INET;
		break;
	case AF_INET6:
		*family_erpc_wifi = ERPC_WIFI_AF_INET6;
		break;
	default:
		return -EAFNOSUPPORT;
		break;
	}

	return 0;
}

static int erpc_wifi_socket_addr_from_posix(const struct sockaddr *addr,
					    struct ra_erpc_sockaddr *addr_erpc_wifi)
{
	int err;

	memset(addr_erpc_wifi, 0, sizeof(struct ra_erpc_sockaddr));

	err = erpc_wifi_socket_family_from_posix(addr->sa_family, &addr_erpc_wifi->sa_family);
	if (err) {
		LOG_ERR("%s - unsupported family: %d", __FUNCTION__, addr->sa_family);
		return err;
	}

	if (addr->sa_family == AF_INET) {
		const struct sockaddr_in *sin = net_sin(addr);
		addr_erpc_wifi->sa_len = 16;
		memcpy(addr_erpc_wifi->sa_data, &sin->sin_port, 2);
		memcpy(&addr_erpc_wifi->sa_data[2], &sin->sin_addr, 4);
	}
#if defined(CONFIG_NET_IPV6)
	else if (addr->sa_family == AF_INET6) {
		const struct sockaddr_in6 *sin6 = net_sin6(addr);
		addr_erpc_wifi->sa_len = 28;
		/* Map Zephyr sockaddr_in6 to RA6W1/LwIP layout (28 bytes in sa_data) */
		/* 0-1: port */
		memcpy(addr_erpc_wifi->sa_data, &sin6->sin6_port, 2);
		/* 2-5: flowinfo (not in Zephyr) */
		memset(&addr_erpc_wifi->sa_data[2], 0, 4);
		/* 6-21: addr */
		memcpy(&addr_erpc_wifi->sa_data[6], &sin6->sin6_addr, 16);
		/* 22-25: scope_id (1 byte in Zephyr, 4 in RA6W1) */
		memset(&addr_erpc_wifi->sa_data[22], 0, 4);
		addr_erpc_wifi->sa_data[22] = sin6->sin6_scope_id;
	}
#endif
	else {
		return -EAFNOSUPPORT;
	}

	return 0;
}

static int erpc_wifi_socket_addr_to_posix(struct sockaddr *addr,
					  struct ra_erpc_sockaddr *addr_erpc_wifi)
{
	int err;

	err = erpc_wifi_socket_family_to_posix(addr_erpc_wifi->sa_family, (int *)&addr->sa_family);
	if (err) {
		LOG_ERR("%s - unsupported family: %d", __FUNCTION__, addr_erpc_wifi->sa_family);
		return err;
	}

	if (addr->sa_family == AF_INET) {
		struct sockaddr_in *sin = net_sin(addr);
		memcpy(&sin->sin_port, addr_erpc_wifi->sa_data, 2);
		memcpy(&sin->sin_addr, &addr_erpc_wifi->sa_data[2], 4);
	}
#if defined(CONFIG_NET_IPV6)
	else if (addr->sa_family == AF_INET6) {
		struct sockaddr_in6 *sin6 = net_sin6(addr);
		/* Map RA6W1/LwIP layout back to Zephyr */
		memcpy(&sin6->sin6_port, addr_erpc_wifi->sa_data, 2);
		/* flowinfo at sa_data[2] is ignored/not in Zephyr */
		memcpy(&sin6->sin6_addr, &addr_erpc_wifi->sa_data[6], 16);
		sin6->sin6_scope_id = addr_erpc_wifi->sa_data[22];
	}
#endif
	else {
		return -EAFNOSUPPORT;
	}

	return 0;
}

static struct erpc_wifi_socket *erpc_wifi_socket_allocate(int fd, int zfd)
{
	struct erpc_wifi_socket *socket = NULL;

	erpc_wifi_lock();
	
	/* If RA6W1 reallocated an FD that Zephyr still thinks is in use (e.g., the RA6W1 implicitly
	 * closed a DHCP UDP socket and reused the FD for a TLS TCP socket), we must force-close
	 * the old Zephyr socket so background threads like DHCP don't steal the new socket's data!
	 */
	for (int i = 0; i < ERPC_WIFI_MAX_SOCKETS; i++) {
		if (sockets[i].in_use && sockets[i].fd == fd) {
			LOG_WRN("RA6W1 FD %d reused! Force-closing stale Zephyr socket (zfd=%d)", 
				fd, sockets[i].zfd);
			sockets[i].in_use = false;
			sockets[i].fd = -1;
			sockets[i].triggered_events |= SOCKET_EVENT_ERR | SOCKET_EVENT_CLOSE;
			if (sockets[i].waiting) {
				k_poll_signal_raise(&sockets[i].poll_signal, 0);
			}
		}
	}

	for (int i = 0; i < ERPC_WIFI_MAX_SOCKETS; i++) {
		if (sockets[i].in_use == false) {
			struct erpc_wifi_socket *s = &sockets[i];
			memset(s, 0, sizeof(*s));
			s->fd = fd;
			s->zfd = zfd;
			s->in_use = true;
			s->waiting = false;
			k_poll_signal_init(&s->poll_signal);
			k_sem_init(&s->read_sem, 0, 1);
			k_fifo_init(&s->fifo);
			s->recv_timeout_ms = 0;
			s->triggered_events = 0;
			socket = s;
			break;
		}
	}
	erpc_wifi_unlock();

	if (socket != NULL) {
		/* Wake the poll task so it begins monitoring the newly allocated socket */
		k_sem_give(&poll_task_sem);
	}

	return socket;
}

static void erpc_wifi_socket_free(struct erpc_wifi_socket *sock)
{
	k_spinlock_key_t key = k_spin_lock(&sock->state_lock);
	sock->in_use = false;
	sock->connected = false;
	sock->connect_pending = false;
	sock->waiting = false;
	k_spin_unlock(&sock->state_lock, key);
}

static int erpc_wifi_socket_bind(void *obj, const struct sockaddr *addr, socklen_t addrlen)
{
	bool ram_held = false;
	int __w = erpc_wifi_ensure_awake_tx(ERPC_PMGR_JOB_ID_SEND, &ram_held);
	if (__w != 0) {
		LOG_INF("erpc_wifi_ensure_awake_tx failed: IN %s = %d", __func__, __w);
		if (ram_held) {
			(void)erpc_wifi_pmgr_ram_release(ERPC_PMGR_JOB_ID_SEND);
		}
		errno = -__w;
		return -1;
	}

	int ret;
	struct ra_erpc_sockaddr addr_erpc_wifi;
	struct erpc_wifi_socket *sock = (struct erpc_wifi_socket *)obj;

	if (sock->tcp_dpm_filter_set && sock->bound_port != 0) {
		erpc_wifi_dpm_tcp_port_delete_t dpm_msg = {.port = sock->bound_port};
		(void)erpc_wifi_send_cmd(ERPC_WIFI_DPM_TCP_PORT_DELETE_CMD, &dpm_msg, sizeof(dpm_msg), -1);
		sock->tcp_dpm_filter_set = false;
		LOG_INF("TCP DPM wake filter removed for port %u (via queue)", sock->bound_port);
	}

	/* Invalidate active TCP job cache on rebind */
	if (sock->bound_port != 0) {
		erpc_wifi_socket_invalidate_active_job_cache();
	}

	sock->bound_port = 0;
	if (addr && addr->sa_family == AF_INET) {
		const struct sockaddr_in *sin = (const struct sockaddr_in *)addr;
		sock->bound_port = ntohs(sin->sin_port);
		LOG_DBG("bind: local port=%u", sock->bound_port);
	}

	LOG_DBG("fd: %d", sock->fd);

	ret = erpc_wifi_socket_addr_from_posix(addr, &addr_erpc_wifi);
	if (ret) {
		if (ram_held) {
			erpc_wifi_pmgr_ram_release(ERPC_PMGR_JOB_ID_SEND);
		}
		erpc_wifi_ps_notify_wakeup();
		errno = -ret;
		return -1;
	}

	/* Use message queue for FIFO-serialized socket operation */
	erpc_wifi_msg_bind_t bind_msg = {
		.fd = sock->fd,
		.addr_erpc_wifi = addr_erpc_wifi
	};
	ret = erpc_wifi_send_cmd(ERPC_WIFI_BIND_CMD, &bind_msg, sizeof(bind_msg), -1);

	if (ram_held) {
		erpc_wifi_pmgr_ram_release(ERPC_PMGR_JOB_ID_SEND);
	}
	erpc_wifi_ps_notify_wakeup();

	LOG_DBG("ra6w1_bind: %d", ret);

	if (ret < 0) {
		errno = -ret;
		return -1;
	}

	return 0;
}

static int erpc_wifi_socket_connect(void *obj, const struct sockaddr *addr, socklen_t addrlen)
{
	erpc_wifi_ps_notify_socket_connect_start();

	bool ram_held = false;
	int __w = erpc_wifi_ensure_awake_tx(ERPC_PMGR_JOB_ID_SEND, &ram_held);
	if (__w != 0) { 
		erpc_wifi_ps_notify_socket_connect_failed();
		LOG_INF("erpc_wifi_ensure_awake_tx failed: IN %s = %d", __func__, __w);
		if (ram_held) {
			erpc_wifi_pmgr_ram_release(ERPC_PMGR_JOB_ID_SEND);
		}
		errno = -__w;
		return -1;
	}
	int ret;
	struct ra_erpc_sockaddr addr_erpc_wifi;
	struct erpc_wifi_socket *sock = (struct erpc_wifi_socket *)obj;

	LOG_DBG("sa_family: %d", addr->sa_family);
	LOG_DBG("addrlen: %d", addrlen);
	LOG_DBG("fd: %d", sock->fd);
	// addr->sa_family = AF_INET6;
	if (addr->sa_family == AF_INET) {
		char addr_str[INET_ADDRSTRLEN];
		struct sockaddr_in *s_addr = net_sin(addr);

		net_addr_ntop(addr->sa_family, &s_addr->sin_addr, addr_str, sizeof(addr_str));
		LOG_DBG("sin: addr: %s port: %d", addr_str, ntohs(s_addr->sin_port));
		if (sock->type == SOCK_STREAM) {
			strncpy(sock->addr_str, addr_str, sizeof(sock->addr_str) - 1);
			sock->addr_str[sizeof(sock->addr_str) - 1] = '\0';
			sock->port = ntohs(s_addr->sin_port);
		}
	}
#if defined(CONFIG_NET_IPV6)
	else if (addr->sa_family == AF_INET6) {
		char addr_str[INET6_ADDRSTRLEN];
		struct sockaddr_in6 *s_addr = net_sin6(addr);

		net_addr_ntop(addr->sa_family, &s_addr->sin6_addr, addr_str, sizeof(addr_str));
		LOG_DBG("sin6: addr: %s port: %d", addr_str, ntohs(s_addr->sin6_port));
		if (sock->type == SOCK_STREAM) {
			strncpy(sock->addr_str, addr_str, sizeof(sock->addr_str) - 1);
			sock->addr_str[sizeof(sock->addr_str) - 1] = '\0';
			sock->port = ntohs(s_addr->sin6_port);
		}
	}
#endif

	if (sock->type == SOCK_STREAM && sock->bound_port == 0) {
		if (sock->family == AF_INET) {
			struct sockaddr_in local_addr = {
				.sin_family = AF_INET,
				.sin_port = htons(55000 + sock->fd),
				.sin_addr = { .s_addr = INADDR_ANY }
			};
			int bind_ret = erpc_wifi_socket_bind(sock, (const struct sockaddr *)&local_addr, sizeof(local_addr));
			if (bind_ret < 0) {
				LOG_WRN("Auto-bind to port %u failed: %d", 55000 + sock->fd, bind_ret);
			} else {
				LOG_INF("Auto-bound TCP client socket to port %u for DPM tracking", 55000 + sock->fd);
			}
		}
#if defined(CONFIG_NET_IPV6)
		else if (sock->family == AF_INET6) {
			struct sockaddr_in6 local_addr6 = {
				.sin6_family = AF_INET6,
				.sin6_port = htons(55000 + sock->fd),
				.sin6_addr = IN6ADDR_ANY_INIT,
			};
			int bind_ret = erpc_wifi_socket_bind(sock, (const struct sockaddr *)&local_addr6, sizeof(local_addr6));
			if (bind_ret < 0) {
				LOG_WRN("Auto-bind IPv6 to port %u failed: %d", 55000 + sock->fd, bind_ret);
			} else {
				LOG_INF("Auto-bound IPv6 TCP client socket to port %u for DPM tracking", 55000 + sock->fd);
			}
		}
#endif
	}

	ret = erpc_wifi_socket_addr_from_posix(addr, &addr_erpc_wifi);
	if (ret) {
		erpc_wifi_ps_notify_socket_connect_failed();
		if (ram_held) {
			erpc_wifi_pmgr_ram_release(ERPC_PMGR_JOB_ID_SEND);
		}
		erpc_wifi_ps_notify_wakeup();
		errno = -ret;
		return -1;
	}

	/* Use message queue for FIFO-serialized socket operation */
	erpc_wifi_msg_connect_t connect_msg = {
		.fd = sock->fd,
		.addr_erpc_wifi = addr_erpc_wifi
	};
	ret = erpc_wifi_send_cmd(ERPC_WIFI_CONNECT_CMD, &connect_msg, sizeof(connect_msg), -1);
	k_msleep(100);

	k_spinlock_key_t key = k_spin_lock(&sock->state_lock);
	if (ret == 0) {
		sock->connected = true;
		sock->connect_pending = false;
		sock->socket_error = 0;
		memcpy(&sock->addr, addr, sizeof(sock->addr));
		sock->addrlen = addrlen;
		k_spin_unlock(&sock->state_lock, key);
		/* Register TCP DPM wake filter BEFORE releasing the RAM/awake constraint.
		 * If done after pmgr_ram_release + ps_notify_wakeup the module may have
		 * started its sleep transition and the eRPC call gets a CRC error.
		 * Now uses queue-based command for thread-safe execution. */
		if (sock->type == SOCK_STREAM && sock->bound_port != 0 &&
		    !sock->tcp_dpm_filter_set) {
			erpc_wifi_dpm_tcp_port_filter_set_t dpm_msg = {.port = sock->bound_port};
			int32_t rc = erpc_wifi_send_cmd(ERPC_WIFI_DPM_TCP_PORT_FILTER_SET_CMD, &dpm_msg, sizeof(dpm_msg), -1);
			if (rc == 0) {
				sock->tcp_dpm_filter_set = true;
				LOG_INF("TCP DPM wake filter set for connected port %u (via queue)",
					sock->bound_port);
			} else {
				LOG_WRN("Failed to set TCP DPM wake filter for connected port %u (rc=%d, via queue)",
					sock->bound_port, rc);
			}
		}
		erpc_wifi_ps_notify_socket_connected();
	} else if (ret == -EINPROGRESS || ret == -EALREADY) {
		sock->connected = false;
		sock->connect_pending = true;
		sock->socket_error = 0;
		k_spin_unlock(&sock->state_lock, key);
		LOG_INF("Non-blocking connect in progress for fd %d", sock->fd);

		if ((sock->flags & O_NONBLOCK) == 0) {
			/* Blocking connect mode: wait for connect_pending to be cleared by poll_task or SO_ERROR fallback */
			int32_t timeout_ms = sock->send_timeout_ms == 0 ? 10000 : sock->send_timeout_ms;
			int64_t start_ms = k_uptime_get();

			while (1) {
				k_spinlock_key_t s_key = k_spin_lock(&sock->state_lock);
				if (!sock->connect_pending) {
					if (sock->connected) {
						ret = 0;
					} else {
						ret = sock->socket_error != 0 ? -sock->socket_error : -ECONNREFUSED;
					}
					k_spin_unlock(&sock->state_lock, s_key);
					break;
				}

				sock->waiting = true;
				sock->poll_events = ZVFS_POLLOUT;
				k_poll_signal_reset(&sock->poll_signal);
				k_spin_unlock(&sock->state_lock, s_key);

				k_sem_give(&poll_task_sem);

				int32_t elapsed_ms = (int32_t)(k_uptime_get() - start_ms);
				if (timeout_ms > 0 && elapsed_ms >= timeout_ms) {
					s_key = k_spin_lock(&sock->state_lock);
					sock->connect_pending = false;
					sock->connected = false;
					sock->socket_error = ETIMEDOUT;
					k_spin_unlock(&sock->state_lock, s_key);

					LOG_WRN("connect wait timeout: fd=%d elapsed=%dms", sock->fd, elapsed_ms);

					ret = -ETIMEDOUT;
					erpc_wifi_ps_notify_socket_connect_failed();
					break;
				}

				int32_t wait_ms = timeout_ms > 0 ? (timeout_ms - elapsed_ms) : 500;
				if (wait_ms > 500) {
					wait_ms = 500;
				}

				struct k_poll_event event;
				k_poll_event_init(&event, K_POLL_TYPE_SIGNAL, K_POLL_MODE_NOTIFY_ONLY, &sock->poll_signal);
				int poll_ret = k_poll(&event, 1, K_MSEC(wait_ms));

				s_key = k_spin_lock(&sock->state_lock);
				sock->waiting = false;
				k_spin_unlock(&sock->state_lock, s_key);

				/* Reconcile state via SO_ERROR fallback if poll timed out or completed */
				if (poll_ret == -EAGAIN || poll_ret == 0) {
					int remote_error = 0;
					socklen_t remote_len = sizeof(remote_error);
					erpc_wifi_msg_sockgetopt_t go_msg = {
						.fd = sock->fd,
						.level = ERPC_WIFI_SOL_SOCKET,
						.optname = ERPC_WIFI_SO_ERROR,
						.optval = (uint32_t *)&remote_error,
						.optlen = &remote_len,
					};
					int so_rc = erpc_wifi_send_cmd(ERPC_WIFI_SOCKET_GETOPT_CMD,
									      &go_msg,
									      sizeof(go_msg),
									      -1);

					if (so_rc == 0) {
						s_key = k_spin_lock(&sock->state_lock);
						if (remote_error == 0) {
							sock->connect_pending = false;
							sock->connected = true;
							sock->socket_error = 0;
						} else if (remote_error != EINPROGRESS && remote_error != EALREADY) {
							sock->connect_pending = false;
							sock->connected = false;
							sock->socket_error = remote_error;
						}
						k_spin_unlock(&sock->state_lock, s_key);

						if (remote_error == 0) {
							LOG_INF("connect fallback: fd=%d completed via SO_ERROR", sock->fd);
						} else if (remote_error != EINPROGRESS && remote_error != EALREADY) {
							LOG_WRN("connect fallback: fd=%d failed via SO_ERROR=%d", sock->fd, remote_error);
						}
					}
				}
			}
		}
	} else {
		sock->connected = false;
		sock->connect_pending = false;
		sock->socket_error = -ret;
		k_spin_unlock(&sock->state_lock, key);
		erpc_wifi_ps_notify_socket_connect_failed();
	}

	if (ram_held) {
		erpc_wifi_pmgr_ram_release(ERPC_PMGR_JOB_ID_SEND);
	}
	erpc_wifi_ps_notify_wakeup();
	LOG_DBG("ra6w1_connect: %d", ret);

	if (ret < 0) {
		errno = -ret;
		return -1;
	}
	return 0;
}

static int erpc_wifi_socket_listen(void *obj, int backlog)
{
	bool ram_held = false;
	int __w = erpc_wifi_ensure_awake_tx(ERPC_PMGR_JOB_ID_SEND, &ram_held);
	if (__w != 0) {
		LOG_INF("erpc_wifi_ensure_awake_tx failed: IN %s = %d", __func__, __w);
		if (ram_held) {
			(void)erpc_wifi_pmgr_ram_release(ERPC_PMGR_JOB_ID_SEND);
		}
		errno = -__w;
		return -1;
	}

	int ret;
	struct erpc_wifi_socket *sock = (struct erpc_wifi_socket *)obj;

	LOG_DBG("fd: %d", sock->fd);
	LOG_DBG("backlog: %d", backlog);

	/* Use message queue for FIFO-serialized socket operation */
	erpc_wifi_msg_listen_t listen_msg = {
		.fd = sock->fd,
		.backlog = backlog
	};
	ret = erpc_wifi_send_cmd(ERPC_WIFI_LISTEN_CMD, &listen_msg, sizeof(listen_msg), -1);

	LOG_DBG("ra6w1_listen: %d", ret);

	/* Register TCP DPM wake filter using queue-based command (thread-safe) */
	if (ret == 0 && sock->type == SOCK_STREAM && sock->bound_port != 0 &&
	    !sock->tcp_dpm_filter_set) {
		erpc_wifi_dpm_tcp_port_filter_set_t dpm_msg = {.port = sock->bound_port};
		int32_t rc = erpc_wifi_send_cmd(ERPC_WIFI_DPM_TCP_PORT_FILTER_SET_CMD, &dpm_msg, sizeof(dpm_msg), -1);
		if (rc == 0) {
			sock->tcp_dpm_filter_set = true;
			LOG_INF("TCP DPM wake filter set for port %u (via queue)", sock->bound_port);
		} else {
			LOG_WRN("Failed to set TCP DPM wake filter for port %u (rc=%d, via queue)",
				sock->bound_port, rc);
		}
	}

	if (ram_held) {
		erpc_wifi_pmgr_ram_release(ERPC_PMGR_JOB_ID_SEND);
	}
	erpc_wifi_ps_notify_wakeup();

	if (ret < 0) {
		errno = -ret;
		return -1;
	}

	return 0;
}

static int erpc_wifi_socket_accept(void *obj, struct sockaddr *addr, socklen_t *addrlen)
{
	int fd;
	int conn_fd;
	struct ra_erpc_sockaddr remote_addr;
	uint32_t remote_addrlen = sizeof(remote_addr);
	struct erpc_wifi_socket *sock = (struct erpc_wifi_socket *)obj;
	struct erpc_wifi_socket *socket;

	LOG_DBG("fd: %d", sock->fd);

	if ((addr == NULL) != (addrlen == NULL)) {
		errno = EINVAL;
		return -1;
	}

	for (;;) {
		k_spinlock_key_t key2 = k_spin_lock(&sock->state_lock);
		if (sock->triggered_events & (SOCKET_EVENT_RX | SOCKET_EVENT_ERR | SOCKET_EVENT_CLOSE)) {
			sock->triggered_events &= ~SOCKET_EVENT_RX;
			k_spin_unlock(&sock->state_lock, key2);
			break;
		}
		
		if (sock->flags & O_NONBLOCK) {
			k_spin_unlock(&sock->state_lock, key2);
			errno = EAGAIN;
			return -1;
		}

		sock->waiting = true;
		sock->poll_events = ZVFS_POLLIN;
		k_poll_signal_reset(&sock->poll_signal);
		k_spin_unlock(&sock->state_lock, key2);
		k_sem_give(&poll_task_sem);

		struct k_poll_event event;
		k_poll_event_init(&event, K_POLL_TYPE_SIGNAL, K_POLL_MODE_NOTIFY_ONLY, &sock->poll_signal);

		int poll_rc = k_poll(&event, 1, K_FOREVER);
		k_spinlock_key_t key3 = k_spin_lock(&sock->state_lock);
		sock->waiting = false;
		k_spin_unlock(&sock->state_lock, key3);

		if (poll_rc < 0 && poll_rc != -EAGAIN) {
			errno = -poll_rc;
			return -1;
		}
	}

	fd = zvfs_reserve_fd();
	if (fd < 0) {
		errno = ENFILE;
		return -1;
	}

	erpc_wifi_ps_hold_during_recv();
	bool rx_ram_held = false;
	int __w = erpc_wifi_ensure_awake_rx(ERPC_PMGR_JOB_ID_RECV, &rx_ram_held);
	if (__w != 0) {
		zvfs_free_fd(fd);
		errno = -__w;
		return -1;
	}

	/* Accept returns file descriptor for new connected socket */
	erpc_wifi_msg_accept_t accept_msg = { .fd = sock->fd, .addr_erpc_wifi = &remote_addr, .addrlen = &remote_addrlen };
	conn_fd = (int)erpc_wifi_send_cmd(ERPC_WIFI_ACCEPT_CMD, &accept_msg, sizeof(accept_msg), -1);
	LOG_DBG("ra6w1_accept: %d", conn_fd);

	if (conn_fd < 0) {
		if (rx_ram_held) {
			int rel_rc = erpc_wifi_pmgr_ram_release(ERPC_PMGR_JOB_ID_RECV);
			if (rel_rc != 0) {
				LOG_ERR("accept POWER_RAM release failed: %d", rel_rc);
			} else {
				rx_ram_held = false;
			}
		}
		erpc_wifi_ps_notify_wakeup();
		zvfs_free_fd(fd);
		errno = -conn_fd;
		return -1;
	}

	if (addr != NULL && addrlen != NULL) {
		socklen_t caller_len = *addrlen;

		if (sock->family == AF_INET && caller_len < sizeof(struct sockaddr_in)) {
			(void)erpc_wifi_send_cmd(ERPC_WIFI_SOCKET_CLOSE_CMD, &conn_fd, sizeof(conn_fd), -1);
			if (rx_ram_held) {
				int rel_rc = erpc_wifi_pmgr_ram_release(ERPC_PMGR_JOB_ID_RECV);
				if (rel_rc != 0) {
					LOG_ERR("accept POWER_RAM release failed: %d", rel_rc);
				} else {
					rx_ram_held = false;
				}
			}
			erpc_wifi_ps_notify_wakeup();
			zvfs_free_fd(fd);
			errno = EINVAL;
			return -1;
		}
#if defined(CONFIG_NET_IPV6)
		if (sock->family == AF_INET6 && caller_len < sizeof(struct sockaddr_in6)) {
			(void)erpc_wifi_send_cmd(ERPC_WIFI_SOCKET_CLOSE_CMD, &conn_fd, sizeof(conn_fd), -1);
			if (rx_ram_held) {
				int rel_rc = erpc_wifi_pmgr_ram_release(ERPC_PMGR_JOB_ID_RECV);
				if (rel_rc != 0) {
					LOG_ERR("accept POWER_RAM release failed: %d", rel_rc);
				} else {
					rx_ram_held = false;
				}
			}
			erpc_wifi_ps_notify_wakeup();
			zvfs_free_fd(fd);
			errno = EINVAL;
			return -1;
		}
#endif

		int ret = erpc_wifi_socket_addr_to_posix(addr, &remote_addr);
		if (ret < 0) {
			(void)erpc_wifi_send_cmd(ERPC_WIFI_SOCKET_CLOSE_CMD, &conn_fd, sizeof(conn_fd), -1);
			if (rx_ram_held) {
				int rel_rc = erpc_wifi_pmgr_ram_release(ERPC_PMGR_JOB_ID_RECV);
				if (rel_rc != 0) {
					LOG_ERR("accept POWER_RAM release failed: %d", rel_rc);
				} else {
					rx_ram_held = false;
				}
			}
			erpc_wifi_ps_notify_wakeup();
			zvfs_free_fd(fd);
			LOG_DBG("erpc_wifi_socket_addr_to_posix error: %d", ret);
			errno = -ret;
			return -1;
		}

		*addrlen = (addr->sa_family == AF_INET6)
			 ? sizeof(struct sockaddr_in6)
			 : sizeof(struct sockaddr_in);
	}

	/* Keep track of the new fd returned by accept */
	socket = erpc_wifi_socket_allocate(conn_fd, fd);

	if (socket == NULL) {
		(void)erpc_wifi_send_cmd(ERPC_WIFI_SOCKET_CLOSE_CMD, &conn_fd, sizeof(conn_fd), -1);
		if (rx_ram_held) {
			int rel_rc = erpc_wifi_pmgr_ram_release(ERPC_PMGR_JOB_ID_RECV);
			if (rel_rc != 0) {
				LOG_ERR("accept POWER_RAM release failed: %d", rel_rc);
			} else {
				rx_ram_held = false;
			}
		}
		erpc_wifi_ps_notify_wakeup();
		zvfs_free_fd(fd);
		errno = ENFILE;
		return -1;
	}

	if (rx_ram_held) {
		int rel_rc = erpc_wifi_pmgr_ram_release(ERPC_PMGR_JOB_ID_RECV);
		if (rel_rc != 0) {
			LOG_ERR("accept POWER_RAM release failed: %d", rel_rc);
		} else {
			rx_ram_held = false;
		}
	}
	erpc_wifi_ps_notify_wakeup();

	socket->family = sock->family;
	socket->type = sock->type;
	socket->protocol = sock->protocol;
	socket->connected = true;
	socket->connect_pending = false;
	socket->socket_error = 0;

	/* Associate zephyr file descriptor with the socket obj and offload table
	   ensures subsequent socket operations using zephyr fd will use the
	       appropriate RA6W1 fd */
	zvfs_finalize_typed_fd(fd, socket,
			       (const struct fd_op_vtable *)&erpc_wifi_socket_fd_op_vtable,
			       ZVFS_MODE_IFSOCK);

	return fd;
}


static void erpc_wifi_sync_recv_job_for_socket_locked(struct erpc_wifi_socket *sock, const char *path)
{
	if (!erpc_wifi_ps_is_enabled()) {
		return;
	}

	if ((sock == NULL) || (sock->type != SOCK_STREAM) || (sock->bound_port == 0U)) {
		return;
	}

	if (g_active_tcp_recv_port == sock->bound_port) {
		return;
	}

	/* PMGR RECV mapping on RA6W1 is global; bind it to the active TCP socket before I/O. */
	erpc_wifi_pmgr_job_name_t jn_msg = { .job_id = (uint32_t)sock->bound_port, .job_name = "ERPC_TCP_RECV" };
	int32_t rc = (int32_t)erpc_wifi_send_cmd(ERPC_WIFI_PMGR_DPM_JOB_NAME_SET_CMD,
										   &jn_msg, sizeof(jn_msg), -1);

	if (rc < 0) {
		LOG_WRN("%s: failed to map ERPC_TCP_RECV to port %u (rc=%d)",
			path ? path : "unknown", sock->bound_port, rc);
		g_active_tcp_recv_port = 0;
	} else {
		g_active_tcp_recv_port = sock->bound_port;
	}
}

static void erpc_wifi_sync_recv_job_for_socket(struct erpc_wifi_socket *sock, const char *path)
{
	k_mutex_lock(&g_active_tcp_job_mutex, K_FOREVER);
	erpc_wifi_sync_recv_job_for_socket_locked(sock, path);
	k_mutex_unlock(&g_active_tcp_job_mutex);
}

static ssize_t erpc_wifi_socket_send_core(struct erpc_wifi_socket *sock, const void *buf, size_t len, int flags,
										   const struct sockaddr *dest_addr, socklen_t addrlen, bool *ram_held)
{
	int ret = 0;
	struct ra_erpc_sockaddr addr_erpc_wifi;
	int ra_flags = 0;
	bool is_nonblock = (flags & ZSOCK_MSG_DONTWAIT) || (sock->flags & O_NONBLOCK);
	uint32_t timeout_ms = sock->send_timeout_ms == 0 ? UINT32_MAX : sock->send_timeout_ms;
	int64_t start_time = k_uptime_get();
	bool poll_waiting = false;

	if ((flags & ZSOCK_MSG_DONTWAIT) || (sock->flags & O_NONBLOCK)) {
		ra_flags |= 0x08;
	}

	if (dest_addr) {
		ret = erpc_wifi_socket_addr_from_posix(dest_addr, &addr_erpc_wifi);
		if (ret) {
			/* Helper already returns a negative errno value. */
			return ret;
		}
	}

	for (;;) {
		/* Acquire job mutex to protect DPM job mapping + SEND/SENDTO command execution */
		k_mutex_lock(&g_active_tcp_job_mutex, K_FOREVER);

		erpc_wifi_sync_recv_job_for_socket_locked(sock, "send_core");

		if (dest_addr) {
			erpc_wifi_msg_sendto_t st_msg = { .fd = sock->fd, .buff = (uint8_t *)buf, .buff_size = len,
											  .flags = ra_flags, .addr_erpc_wifi = &addr_erpc_wifi };
			ret = erpc_wifi_send_cmd(ERPC_WIFI_SENDTO_CMD, &st_msg, sizeof(st_msg), -1);
			LOG_DBG("ra6w1_sendto: %d", ret);
		} else {
			erpc_wifi_msg_send_t s_msg = { .fd = sock->fd, .buff = (uint8_t *)buf, .buff_size = len,
										   .flags = ra_flags };
			ret = erpc_wifi_send_cmd(ERPC_WIFI_SEND_CMD, &s_msg, sizeof(s_msg), -1);
			LOG_DBG("ra6w1_send: %d", ret);
		}

		k_mutex_unlock(&g_active_tcp_job_mutex);

		if (ret >= 0) {
			break;
		}

		if (ret != -EAGAIN && ret != -EWOULDBLOCK) {
			break;
		}

		if (is_nonblock) {
			k_spinlock_key_t key = k_spin_lock(&sock->state_lock);
			sock->triggered_events &= ~SOCKET_EVENT_TX;
			k_spin_unlock(&sock->state_lock, key);
			break;
		}

		/* Blocking mode: wait for POLLOUT */
		int64_t elapsed = k_uptime_get() - start_time;
		if (timeout_ms != UINT32_MAX && elapsed >= (int64_t)timeout_ms) {
			ret = -ETIMEDOUT;
			break;
		}

		k_timeout_t rem_timeout = (timeout_ms == UINT32_MAX) ? K_FOREVER : K_MSEC(timeout_ms - elapsed);

		k_spinlock_key_t key = k_spin_lock(&sock->state_lock);
		if (sock->triggered_events & (SOCKET_EVENT_ERR | SOCKET_EVENT_CLOSE)) {
			k_spin_unlock(&sock->state_lock, key);
			ret = -EPIPE;
			break;
		}
		sock->triggered_events &= ~SOCKET_EVENT_TX;
		sock->waiting = true;
		sock->poll_events = ZVFS_POLLOUT;
		k_poll_signal_reset(&sock->poll_signal);
		k_spin_unlock(&sock->state_lock, key);

		poll_waiting = true;
		k_sem_give(&poll_task_sem);

		struct k_poll_event event;
		k_poll_event_init(&event, K_POLL_TYPE_SIGNAL, K_POLL_MODE_NOTIFY_ONLY, &sock->poll_signal);

		/* Release constraints while blocked */
		if (*ram_held) {
			int rel_rc = erpc_wifi_pmgr_ram_release(ERPC_PMGR_JOB_ID_SEND);
			if (rel_rc != 0) {
				ret = rel_rc;
				break;
			}
			*ram_held = false;
			erpc_wifi_ps_notify_wakeup();
		}

		int poll_rc = k_poll(&event, 1, rem_timeout);

		int __w2 = erpc_wifi_ensure_awake_tx(ERPC_PMGR_JOB_ID_SEND, ram_held);
		if (__w2 != 0) {
			ret = __w2;
			break;
		}

		key = k_spin_lock(&sock->state_lock);
		sock->waiting = false;
		poll_waiting = false;
		k_spin_unlock(&sock->state_lock, key);

		if (poll_rc != 0) {
			ret = -ETIMEDOUT;
			break;
		}
	}

	if (poll_waiting) {
		k_spinlock_key_t key = k_spin_lock(&sock->state_lock);
		sock->waiting = false;
		k_spin_unlock(&sock->state_lock, key);
	}
	return ret;
}

static ssize_t erpc_wifi_socket_sendto(void *obj, const void *buf, size_t len, int flags,
				       const struct sockaddr *dest_addr, socklen_t addrlen)
{
	LOG_DBG("TX wake request (len=%u)", (unsigned int)len);

	bool ram_held = false;
	int __w = erpc_wifi_ensure_awake_tx(ERPC_PMGR_JOB_ID_SEND, &ram_held);
	if (__w != 0) { 
		LOG_INF("erpc_wifi_ensure_awake_tx failed: IN %s = %d", __func__, __w);
		if (ram_held) {
			(void)erpc_wifi_pmgr_ram_release(ERPC_PMGR_JOB_ID_SEND);
		}
		errno = -__w;
		return -1;
	}

	struct erpc_wifi_socket *sock = (struct erpc_wifi_socket *)obj;
	ssize_t ret = erpc_wifi_socket_send_core(sock, buf, len, flags, dest_addr, addrlen, &ram_held);

	if (ret < 0) {
		if (ram_held) {
			(void)erpc_wifi_pmgr_ram_release(ERPC_PMGR_JOB_ID_SEND);
		}
		if (ret != -EAGAIN) {
			erpc_wifi_ps_notify_wakeup();
		}
		errno = -ret;
		return -1;
	}

	if (ram_held) {
		(void)erpc_wifi_pmgr_ram_release(ERPC_PMGR_JOB_ID_SEND);
	}
	erpc_wifi_ps_notify_wakeup();

	return ret;
}

ssize_t erpc_wifi_socket_sendmsg(void *obj, const struct msghdr *msg, int flags)
{
	if (msg->msg_iov) {
		bool ram_held = false;
		int __w = erpc_wifi_ensure_awake_tx(ERPC_PMGR_JOB_ID_SEND, &ram_held);
		if (__w != 0) {
			LOG_INF("erpc_wifi_ensure_awake_tx failed: IN %s = %d", __func__, __w);
			if (ram_held) {
				(void)erpc_wifi_pmgr_ram_release(ERPC_PMGR_JOB_ID_SEND);
			}
			errno = -__w;
			return -1;
		}

		struct erpc_wifi_socket *sock = (struct erpc_wifi_socket *)obj;
		ssize_t len = 0;

		for (int i = 0; i < msg->msg_iovlen; i++) {
			int ret = erpc_wifi_socket_send_core(sock, msg->msg_iov[i].iov_base,
							  msg->msg_iov[i].iov_len, flags, NULL, 0, &ram_held);

			if (ret < 0) {
				if (ram_held) {
					(void)erpc_wifi_pmgr_ram_release(ERPC_PMGR_JOB_ID_SEND);
				}
				if (ret != -EAGAIN) {
					erpc_wifi_ps_notify_wakeup();
				}
				if (len > 0) {
					return len;
				}
				errno = -ret;
				return -1;
			}

			len += ret;
			if (ret < msg->msg_iov[i].iov_len) {
				break;
			}
		}

		if (ram_held) {
			(void)erpc_wifi_pmgr_ram_release(ERPC_PMGR_JOB_ID_SEND);
		}
		erpc_wifi_ps_notify_wakeup();

		return len;
	}

	errno = EINVAL;
	return -1;
}

static ssize_t erpc_wifi_socket_recvfrom(void *obj, void *buf, size_t max_len, int flags,
					 struct sockaddr *src_addr, socklen_t *addrlen)
{
	struct erpc_wifi_socket *sock = (struct erpc_wifi_socket *)obj;
	bool mutex_locked = false;

	bool is_nonblock = (sock->flags & O_NONBLOCK) || (flags & ZSOCK_MSG_DONTWAIT);
	if (is_nonblock) {
		LOG_DBG("Non-blocking recvfrom requested (fd=%d)", sock->fd);
		k_spinlock_key_t key = k_spin_lock(&sock->state_lock);
		bool no_data = !(sock->triggered_events & (SOCKET_EVENT_RX | SOCKET_EVENT_ERR | SOCKET_EVENT_CLOSE));
		k_spin_unlock(&sock->state_lock, key);

		/* Return EAGAIN early if PS is enabled, module is in DPM sleep, and no
		 * events have been confirmed by the poll task yet. */
		if (erpc_wifi_ps_is_enabled() && !erpc_wifi_ps_is_module_awake() && no_data) {
			errno = EAGAIN;
			return -1;
		}
	}

	int64_t start_time = k_uptime_get();
	uint32_t timeout_ms = sock->recv_timeout_ms;
	if (timeout_ms == 0) {
		timeout_ms = UINT32_MAX; // infinite
	}

	int ret;

	/*
	 * Only cancel the pending sleep work once for this
	 * application receive operation.
	 *
	 * Do NOT cancel/restart the 5-second DPM timer on
	 * every internal EAGAIN retry.
	 */
	bool recv_ps_hold_started = false;
	bool recv_wait_sleep_armed = false;

	for (;;) {
		if (sock->type == SOCK_STREAM && !mutex_locked) {
			k_mutex_lock(&g_active_tcp_job_mutex, K_FOREVER);
			mutex_locked = true;
		}

		if (!recv_ps_hold_started) {
			erpc_wifi_ps_hold_during_recv();
			recv_ps_hold_started = true;
		}

		/* Rebind global RECV mapping before wake/ready prep so ensure_awake_rx
		 * and subsequent recv operate on the same TCP socket context. */
		erpc_wifi_sync_recv_job_for_socket_locked(sock, "recvfrom-prewake");

		bool rx_ram_held = false;
		int __w = erpc_wifi_ensure_awake_rx(ERPC_PMGR_JOB_ID_RECV, &rx_ram_held);
		if (__w != 0) {
			LOG_DBG("erpc_wifi_ensure_awake_rx not ready: %d", __w);
			if (rx_ram_held) {
				int rel_rc = erpc_wifi_pmgr_ram_release(ERPC_PMGR_JOB_ID_RECV);
				if (rel_rc != 0) {
					LOG_ERR("recvfrom POWER_RAM release failed: %d", rel_rc);
				} else {
					rx_ram_held = false;
				}
			}
			if (mutex_locked) {
				k_mutex_unlock(&g_active_tcp_job_mutex);
				mutex_locked = false;
			}
			if (is_nonblock) {
				errno = EAGAIN;
				return -1;
			}
			/* Blocking socket: module asleep, wait for poll task to signal RX event */
			{
				int64_t el = k_uptime_get() - start_time;
				if (timeout_ms != UINT32_MAX && el >= (int64_t)timeout_ms) {
					errno = EAGAIN;
					return -1;
				}
				k_timeout_t wt = (timeout_ms == UINT32_MAX) ? K_FOREVER : K_MSEC(timeout_ms - el);
				k_spinlock_key_t kw = k_spin_lock(&sock->state_lock);
				if (!(sock->triggered_events & (SOCKET_EVENT_RX | SOCKET_EVENT_ERR | SOCKET_EVENT_CLOSE))) {
					sock->waiting = true;
					sock->poll_events = ZVFS_POLLIN;
					k_poll_signal_reset(&sock->poll_signal);
					k_spin_unlock(&sock->state_lock, kw);
					k_sem_give(&poll_task_sem);
					struct k_poll_event pev;
					k_poll_event_init(&pev, K_POLL_TYPE_SIGNAL, K_POLL_MODE_NOTIFY_ONLY, &sock->poll_signal);
					(void)k_poll(&pev, 1, wt);
					kw = k_spin_lock(&sock->state_lock);
					sock->waiting = false;
				}
				k_spin_unlock(&sock->state_lock, kw);
			}
			continue; /* retry ensure_awake_rx */
		}

		erpc_wifi_ps_hold_awake("recv-blocking");

		LOG_DBG("fd: %d", sock->fd);
		LOG_DBG("max_len: %d", max_len);
		LOG_DBG("src_addr: %x", (uint32_t)src_addr);
		LOG_DBG("addrlen: %x", (uint32_t)addrlen);

		int ra_flags = 0x08;
		if (flags & ZSOCK_MSG_PEEK) {
			ra_flags |= 0x02;
		}

		if (src_addr && sock->type != SOCK_STREAM) {
			struct ra_erpc_sockaddr addr_erpc_wifi;
			uint32_t addrlen_erpc = sizeof(struct ra_erpc_sockaddr);

			erpc_wifi_msg_recvfrom_t rf_msg = { .fd = sock->fd, .buff = buf, .buff_size = max_len,
											   .flags = ra_flags, .src_addr = &addr_erpc_wifi,
											   .src_addrlen = &addrlen_erpc };
			ret = erpc_wifi_send_cmd(ERPC_WIFI_RECVFROM_CMD, &rf_msg, sizeof(rf_msg), -1);
			LOG_DBG("ra6w1_recvfrom non-blocking: %d", ret);

			if (ret >= 0) {
				int translate_rc = erpc_wifi_socket_addr_to_posix(src_addr, &addr_erpc_wifi);
				if (translate_rc < 0) {
					LOG_ERR("erpc_wifi_socket_addr_to_posix failed: %d", translate_rc);
				} else {
					if (addrlen) {
						*addrlen = (src_addr->sa_family == AF_INET6) ?
								sizeof(struct sockaddr_in6) : sizeof(struct sockaddr_in);
					}
				}

				LOG_DBG("family: %d", src_addr->sa_family);
				LOG_DBG("address: %d.%d.%d.%d", src_addr->data[2], src_addr->data[3],
					src_addr->data[4], src_addr->data[5]);
				LOG_DBG("port: %d", ((struct sockaddr_in *)src_addr)->sin_port);

				if (addrlen) {
					LOG_DBG("addrlen: %d", *addrlen);
				}
			}
		} else {
			if (sock->type == SOCK_STREAM) {
				erpc_wifi_pmgr_job_t job_msg = { .job_id = ERPC_PMGR_JOB_ID_RECV };
				(void)erpc_wifi_send_cmd(ERPC_WIFI_PMGR_DPM_RCV_READY_SET_CMD,
									   &job_msg, sizeof(job_msg), -1);
			}
			erpc_wifi_msg_recv_t r_msg = { .fd = sock->fd, .buff = buf, .buff_size = max_len,
									  .flags = ra_flags };
			ret = erpc_wifi_send_cmd(ERPC_WIFI_RECV_CMD, &r_msg, sizeof(r_msg), -1);

			if (ret >= 0 && src_addr && sock->type == SOCK_STREAM) {
				struct sockaddr_in *sin = net_sin(src_addr);

				(void)memset(sin, 0, sizeof(*sin));
				sin->sin_family = AF_INET;
				sin->sin_port = htons((uint16_t)sock->port);
				if (sock->addr_str[0] != '\0') {
					(void)net_addr_pton(AF_INET, sock->addr_str, &sin->sin_addr);
				}
				if (addrlen) {
					*addrlen = sizeof(struct sockaddr_in);
				}
			}
		}

		if (rx_ram_held) {
			int rel_rc = erpc_wifi_pmgr_ram_release(ERPC_PMGR_JOB_ID_RECV);
			if (rel_rc != 0) {
				LOG_ERR("RX POWER_RAM release failed: %d", rel_rc);
			} else {
				rx_ram_held = false;
			}
		}

		/*
		 * RA uses -1/EAGAIN-like returns to mean
		 * "socket currently has no data".
		 *
		 * That is NOT network activity and must not keep
		 * pushing the DPM idle timer into the future.
		 */
		bool no_data =
			(ret == -EAGAIN) ||
			(ret == -EWOULDBLOCK) ||
			(ret == -6) ||
			(ret == -1);

		if (no_data) {
			/*
			 * The previous RX readiness notification has now
			 * been consumed and proved stale/no-data.
			 *
			 * Clear ONLY RX. Preserve ERR/CLOSE.
			 */
			k_spinlock_key_t rx_key =
				k_spin_lock(&sock->state_lock);

			sock->triggered_events &= ~SOCKET_EVENT_RX;

			k_spin_unlock(&sock->state_lock, rx_key);

			/*
			 * hold_during_recv() cancelled the previous idle
			 * timer. Re-arm it ONCE while we wait for real data.
			 *
			 * Subsequent stale EAGAIN retries must NOT keep
			 * restarting the 5-second timer.
			 */
			if (!recv_wait_sleep_armed) {
				erpc_wifi_ps_schedule_sleep("recv-wait-no-data");
				recv_wait_sleep_armed = true;
			}
		} else {
			/*
			 * Actual RX/data/error activity.
			 * Restart idle window from this genuine operation.
			 */
			(void)erpc_wifi_ps_notify_wakeup();
		}

		if (mutex_locked) {
			k_mutex_unlock(&g_active_tcp_job_mutex);
			mutex_locked = false;
		}

		/*
		 * RA6W1 non-blocking recv may return -1 for "no data yet" instead of
		 * -EAGAIN/-EWOULDBLOCK. Treat it as transient so higher layers can
		 * continue polling during TLS handshake.
		 */
		if (ret >= 0 || (ret != -EAGAIN && ret != -EWOULDBLOCK && ret != -6 && ret != -1)) {
			if (ret < 0) {
				LOG_ERR("ra6w1_recv failed: %d", ret);
				errno = (ret == -1) ? EIO : (int)-ret;
				return -1;
			}

			/*
			 * TCP/TLS is a byte stream.  A positive recv means only that some
			 * bytes were consumed; TLS commonly reads a 5-byte record header and
			 * then the record body in a second recv().
			 *
			 * Keep RX latched after a positive stream read.  The existing no_data
			 * path clears RX when a later recv actually returns EAGAIN/no-data.
			 * Datagram sockets keep the existing clear-after-one-datagram behavior.
			 */
			if (sock->type != SOCK_STREAM || ret == 0) {
				k_spinlock_key_t key = k_spin_lock(&sock->state_lock);
				sock->triggered_events &= ~SOCKET_EVENT_RX;
				k_spin_unlock(&sock->state_lock, key);
			}

			return ret;
		}
		/* If MSG_DONTWAIT was specified in this call, or O_NONBLOCK is configured on the socket,
		 * return -EAGAIN immediately.
		 */
		if ((flags & ZSOCK_MSG_DONTWAIT) || (sock->flags & O_NONBLOCK)) {
			/* Nonblocking consumer is exiting now; drop stale RX latch to avoid
			 * immediate spin/rearm loops from old readiness state. */
			k_spinlock_key_t key_nb = k_spin_lock(&sock->state_lock);
			sock->triggered_events &= ~SOCKET_EVENT_RX;
			k_spin_unlock(&sock->state_lock, key_nb);
			errno = EAGAIN;
			return -1;
		}
		/* Check if our receive timeout has expired. */
		int64_t elapsed = k_uptime_get() - start_time;
		if (timeout_ms != UINT32_MAX && elapsed >= (int64_t)timeout_ms) {
			errno = EAGAIN;
			return -1;
		}

		/* Calculate remaining timeout for the poll block. */
		k_timeout_t rem_timeout = (timeout_ms == UINT32_MAX) ? K_FOREVER : K_MSEC(timeout_ms - elapsed);

		k_spinlock_key_t key2 = k_spin_lock(&sock->state_lock);
		if (sock->triggered_events & (SOCKET_EVENT_RX | SOCKET_EVENT_ERR | SOCKET_EVENT_CLOSE)) {
			k_spin_unlock(&sock->state_lock, key2);
			continue;
		}
		sock->triggered_events &= ~SOCKET_EVENT_RX;
		sock->waiting = true;
		sock->poll_events = ZVFS_POLLIN;
		k_poll_signal_reset(&sock->poll_signal);
		k_spin_unlock(&sock->state_lock, key2);
		k_sem_give(&poll_task_sem);

		struct k_poll_event event;
		k_poll_event_init(&event, K_POLL_TYPE_SIGNAL, K_POLL_MODE_NOTIFY_ONLY, &sock->poll_signal);

		LOG_DBG("recvfrom: blocking on poll signal, remaining tmo: %lld ms", 
			(timeout_ms == UINT32_MAX) ? -1LL : (int64_t)(timeout_ms - elapsed));
		
		int poll_rc = k_poll(&event, 1, rem_timeout);
		k_spinlock_key_t key3 = k_spin_lock(&sock->state_lock);
		sock->waiting = false;
		k_spin_unlock(&sock->state_lock, key3);

		if (poll_rc != 0) {
			/* k_poll returned a timeout or error. */
			errno = EAGAIN;
			return -1;
		}

		/* Poll task signaled that data has arrived (SOCKET_EVENT_RX). Retry the non-blocking read. */
		LOG_DBG("recvfrom: poll signal raised, retrying read");
	}
}

static int erpc_wifi_socket_getsockopt(void *obj, int level, int optname, void *optval,
				       socklen_t *optlen)
{
	struct erpc_wifi_socket *sock = (struct erpc_wifi_socket *)obj;

	if (!sock) {
		errno = EINVAL;
		return -1;
	}

	bool ram_held = false;
	int __w = erpc_wifi_ensure_awake_tx(ERPC_PMGR_JOB_ID_SEND, &ram_held);
	if (__w != 0) {
		LOG_WRN("erpc_wifi_ensure_awake_tx warning in %s: %d", __func__, __w);
		if (ram_held) {
			(void)erpc_wifi_pmgr_ram_release(0);
		}
		if (level == SOL_SOCKET && optname == SO_ERROR) {
			if (optval != NULL && optlen != NULL && *optlen >= sizeof(int)) {
				*(int *)optval = sock->socket_error;
				*optlen = sizeof(int);
				return 0;
			}
		}
		errno = -__w;
		return -1;
	}

	if (level == SOL_SOCKET && optname == SO_ERROR) {
		int remote_error = 0;
		socklen_t remote_len = sizeof(remote_error);

		if (optval == NULL || optlen == NULL ||
		    *optlen < sizeof(remote_error)) {
			if (ram_held) {
				erpc_wifi_pmgr_ram_release(0);
			}
			erpc_wifi_ps_notify_wakeup();
			errno = EINVAL;
			return -1;
		}

		erpc_wifi_msg_sockgetopt_t go_msg = { .fd = sock->fd, .level = ERPC_WIFI_SOL_SOCKET,
										  .optname = ERPC_WIFI_SO_ERROR,
										  .optval = (uint32_t *)&remote_error, .optlen = &remote_len };
		int rc = erpc_wifi_send_cmd(ERPC_WIFI_SOCKET_GETOPT_CMD, &go_msg, sizeof(go_msg), -1);

		if (ram_held) {
			erpc_wifi_pmgr_ram_release(0);
		}
		erpc_wifi_ps_notify_wakeup();

		if (rc < 0) {
			errno = -rc;
			return -1;
		}

		*(int *)optval = remote_error;
		*optlen = sizeof(remote_error);

		k_spinlock_key_t key = k_spin_lock(&sock->state_lock);
		if (remote_error == 0) {
			sock->socket_error = 0;
			sock->triggered_events &= ~SOCKET_EVENT_ERR;
			if (sock->connect_pending && (sock->triggered_events & SOCKET_EVENT_TX)) {
				sock->connect_pending = false;
				sock->connected = true;
			}
		} else {
			sock->connected = false;
			sock->connect_pending = false;
			sock->socket_error = remote_error;
		}
		k_spin_unlock(&sock->state_lock, key);

		LOG_INF("SO_ERROR fd=%d rc=%d value=%d", sock->fd, rc, remote_error);
		return 0;
	}

	int ret;
	int level_erpc_wifi;
	int optname_erpc_wifi;

	LOG_DBG("level: %d", level);
	LOG_DBG("optname: %d", optname);

	ret = erpc_wifi_socket_level_from_posix(level, &level_erpc_wifi);
	if (ret) {
		if (ram_held) {
			erpc_wifi_pmgr_ram_release(0);
		}
		erpc_wifi_ps_notify_wakeup();
		errno = -ret;
		return -1;
	}

	ret = erpc_wifi_socket_option_from_posix(level, optname, &optname_erpc_wifi);
	if (ret) {
		if (ram_held) {
			erpc_wifi_pmgr_ram_release(0);
		}
		erpc_wifi_ps_notify_wakeup();
		errno = -ret;
		return -1;
	}

	erpc_wifi_msg_sockgetopt_t go_msg2 = { .fd = sock->fd, .level = level_erpc_wifi,
									   .optname = optname_erpc_wifi,
									   .optval = optval, .optlen = optlen };
	ret = erpc_wifi_send_cmd(ERPC_WIFI_SOCKET_GETOPT_CMD, &go_msg2, sizeof(go_msg2), -1);

	if (ram_held) {
		erpc_wifi_pmgr_ram_release(0);
	}
	erpc_wifi_ps_notify_wakeup();
	LOG_DBG("ra6w1_getsockopt: %d", ret);

	if (ret < 0) {
		errno = -ret;
		return -1;
	}

	return 0;
}

static int erpc_wifi_socket_setsockopt(void *obj, int level, int optname, const void *optval,
				       socklen_t optlen)
{
	bool ram_held = false;
	int __w = erpc_wifi_ensure_awake_tx(ERPC_PMGR_JOB_ID_SEND, &ram_held);
	if (__w != 0) { 
		LOG_INF("erpc_wifi_ensure_awake_tx failed: IN %s = %d", __func__,__w);
		if (ram_held) {
			(void)erpc_wifi_pmgr_ram_release(0);
		}
		errno = -__w;
		return -1;
	}

	int ret;
	int level_erpc_wifi;
	int optname_erpc_wifi;
	struct erpc_wifi_socket *sock = (struct erpc_wifi_socket *)obj;

	LOG_DBG("level: %d", level);
	LOG_DBG("optname: %d", optname);
	printk("TLS setsockopt: fd=%d level=%d opt=%d len=%d\n", sock ? sock->fd : -1, level,
	       optname, optlen);

	if (level == SOL_SOCKET && optname == SO_RCVTIMEO && optval != NULL && optlen >= sizeof(struct timeval)) {
		const struct timeval *tv = (const struct timeval *)optval;
		sock->recv_timeout_ms = (uint32_t)(tv->tv_sec * 1000 + tv->tv_usec / 1000);
	}

	if (level == SOL_SOCKET && optname == SO_SNDTIMEO && optval != NULL && optlen >= sizeof(struct timeval)) {
		const struct timeval *tv = (const struct timeval *)optval;
		sock->send_timeout_ms = (uint32_t)(tv->tv_sec * 1000 + tv->tv_usec / 1000);
	}

	ret = erpc_wifi_socket_level_from_posix(level, &level_erpc_wifi);
	if (ret) {
		if (ram_held) {
			erpc_wifi_pmgr_ram_release(0);
		}
		erpc_wifi_ps_notify_wakeup();
		errno = -ret;
		return -1;
	}

	ret = erpc_wifi_socket_option_from_posix(level, optname, &optname_erpc_wifi);
	if (ret) {
		if (ram_held) {
			erpc_wifi_pmgr_ram_release(0);
		}
		erpc_wifi_ps_notify_wakeup();
		errno = -ret;
		return -1;
	}

	erpc_wifi_msg_socksetopt_t so_msg = { .fd = sock->fd, .level = level_erpc_wifi,
									  .optname = optname_erpc_wifi,
									  .optval = (uint32_t *)optval, .optlen = optlen };
	ret = erpc_wifi_send_cmd(ERPC_WIFI_SOCKET_SETOPT_CMD, &so_msg, sizeof(so_msg), -1);

	if (ram_held) {
		erpc_wifi_pmgr_ram_release(0);
	}
	erpc_wifi_ps_notify_wakeup();
	LOG_DBG("ra6w1_setsockopt: %d", ret);

	if (ret < 0) {
		errno = -ret;
		return -1;
	}

	return 0;
}

static ssize_t erpc_wifi_socket_read(void *obj, void *buf, size_t sz)
{
	return erpc_wifi_socket_recvfrom(obj, buf, sz, 0, NULL, NULL);
}

static ssize_t erpc_wifi_socket_write(void *obj, const void *buf, size_t sz)
{
	return erpc_wifi_socket_sendto(obj, buf, sz, 0, NULL, 0);
}

static int erpc_wifi_socket_close(void *obj)
{
	bool ram_held = false;
	int __w = erpc_wifi_ensure_awake_tx(ERPC_PMGR_JOB_ID_SEND, &ram_held);
	if (__w != 0) {
		LOG_WRN("erpc_wifi_ensure_awake_tx warning in %s: %d (proceeding with best-effort close)", __func__, __w);
	}

	int ret = 0;
	struct erpc_wifi_socket *sock = (struct erpc_wifi_socket *)obj;

	if (!sock) {
		if (ram_held) {
			(void)erpc_wifi_pmgr_ram_release(ERPC_PMGR_JOB_ID_SEND);
		}
		return 0;
	}

	LOG_DBG("erpc_wifi_socket_close fd=%d zfd=%d", sock->fd, sock->zfd);

	if (sock->type == SOCK_DGRAM) {
		LOG_INF("UDP socket closed");
	}

	bool was_waiting = false;
	bool notify_failed = false;
	int log_fd = -1;

	k_spinlock_key_t key = k_spin_lock(&sock->state_lock);
	sock->closing = true;
	if (sock->connect_pending) {
		sock->connect_pending = false;
		notify_failed = true;
		log_fd = sock->fd;
	}
	sock->connected = false;
	if (sock->waiting) {
		was_waiting = true;
		sock->waiting = false;
	}
	sock->triggered_events |= SOCKET_EVENT_CLOSE;
	k_spin_unlock(&sock->state_lock, key);

	if (notify_failed) {
		erpc_wifi_ps_notify_socket_connect_failed();
		LOG_INF("Pending connection check canceled for fd %d", log_fd);
	}

	if (was_waiting) {
		k_poll_signal_raise(&sock->poll_signal, SOCKET_EVENT_CLOSE);
	}

	if (sock->tcp_dpm_filter_set && sock->bound_port != 0) {
		erpc_wifi_dpm_tcp_port_delete_t dpm_msg = {.port = sock->bound_port};
		(void)erpc_wifi_send_cmd(ERPC_WIFI_DPM_TCP_PORT_DELETE_CMD, &dpm_msg, sizeof(dpm_msg), -1);
		sock->tcp_dpm_filter_set = false;
		LOG_INF("TCP DPM wake filter removed for port %u (via queue)", sock->bound_port);
	}

	/* Always attempt to close remote FD on RA6W1 to prevent socket leak */
	if (sock->fd >= 0) {
		int remote_fd = sock->fd;
		ret = erpc_wifi_send_cmd(ERPC_WIFI_SOCKET_CLOSE_CMD, &sock->fd, sizeof(sock->fd), -1);
		LOG_INF("Remote socket close fd=%d rc=%d", remote_fd, ret);
	}

	/* Invalidate active TCP job cache unconditionally for closing TCP socket with valid bound port */
	if (sock->type == SOCK_STREAM && sock->bound_port != 0) {
		erpc_wifi_socket_invalidate_active_job_cache();
	}

	if (ram_held) {
		(void)erpc_wifi_pmgr_ram_release(ERPC_PMGR_JOB_ID_SEND);
	}
	erpc_wifi_ps_notify_wakeup();
	LOG_DBG("ra6w1_close: %d", ret);

	if (sock->lock != NULL) {
		k_mutex_unlock(sock->lock);
	}

	/* Unconditionally free driver socket state so slot is reusable */
	erpc_wifi_socket_free(sock);

	return 0;
}

static struct erpc_wifi_socket *find_socket_by_fd(int zfd)
{
	for (int i = 0; i < ERPC_WIFI_MAX_SOCKETS; i++) {
		if (sockets[i].in_use && sockets[i].zfd == zfd) {
			return &sockets[i];
		}
	}

	return NULL;
}

static int erpc_wifi_socket_poll_offload(struct zvfs_pollfd *fds, int nfds, int timeout)
{
	struct k_poll_event events[ERPC_WIFI_MAX_SOCKETS];
	struct erpc_wifi_socket *tracked_socks[ERPC_WIFI_MAX_SOCKETS];
	int tracked_count = 0;
	int ready_count = 0;
	LOG_INF("poll offload start nfds=%d timeout=%d", nfds, timeout);

	ensure_poll_task_started();

	bool immediate_ready = false;
	for (int i = 0; i < nfds; i++) {
		fds[i].revents = 0;
		struct erpc_wifi_socket *sock = find_socket_by_fd(fds[i].fd);

		if (!sock) {
			/* Mixed fd tables are valid in Zephyr (e.g. socket_service eventfd).
			 * Leave non-driver fds untouched so their owner can handle them.
			 */
			continue;
		}

		/* Synthetically report ZVFS_POLLOUT if requested, 
		   unless we are waiting for a background connect to finish. */
		bool notify_connected = false;
		k_spinlock_key_t key = k_spin_lock(&sock->state_lock);
		uint32_t cached = (uint32_t)sock->triggered_events;
		uint32_t requested_mask = 0;
		if (fds[i].events & ZVFS_POLLIN) {
			requested_mask |= SOCKET_EVENT_RX;
		}
		if (fds[i].events & ZVFS_POLLOUT) {
			requested_mask |= SOCKET_EVENT_TX;
		}
		if (fds[i].events & ZVFS_POLLERR) {
			requested_mask |= SOCKET_EVENT_ERR;
		}
		if (fds[i].events & ZVFS_POLLHUP) {
			requested_mask |= SOCKET_EVENT_CLOSE;
		}

		if (sock->connect_pending && (cached & SOCKET_EVENT_TX)) {
			sock->connect_pending = false;
			sock->connected = true;
			sock->socket_error = 0;
			notify_connected = true;
		}

		bool writable = (sock->type == SOCK_DGRAM) ||
				(sock->type == SOCK_STREAM && sock->connected && !sock->connect_pending && sock->socket_error == 0);

		/* Synthetically report ZVFS_POLLOUT if writable and requested */
		if ((fds[i].events & ZVFS_POLLOUT) && writable) {
			fds[i].revents |= ZVFS_POLLOUT;
			sock->triggered_events |= SOCKET_EVENT_TX;
			immediate_ready = true;
			k_spin_unlock(&sock->state_lock, key);
			if (notify_connected) {
				erpc_wifi_ps_notify_socket_connected();
			}
			continue;
		}

		uint32_t ready = sock->triggered_events & requested_mask;
		if (ready != 0) {
			/* Already has ready events, will be filled in update_revents. Just continue without blocking. */
			immediate_ready = true;
			k_spin_unlock(&sock->state_lock, key);
			if (notify_connected) {
				erpc_wifi_ps_notify_socket_connected();
			}
			continue;
		}

		if (tracked_count < ERPC_WIFI_MAX_SOCKETS) {
			k_poll_signal_reset(&sock->poll_signal);
			sock->poll_events = fds[i].events;
			sock->waiting = true;

			k_poll_event_init(&events[tracked_count], K_POLL_TYPE_SIGNAL,
					  K_POLL_MODE_NOTIFY_ONLY, &sock->poll_signal);
			tracked_socks[tracked_count] = sock;
			tracked_count++;
		}
		k_spin_unlock(&sock->state_lock, key);

		if (notify_connected) {
			erpc_wifi_ps_notify_socket_connected();
		}
	}

	if (tracked_count > 0) {
		k_sem_give(&poll_task_sem);
	}

	/* Short-circuit poll with POLLHUP when interface is already down. */
	int hup_count = erpc_wifi_poll_hup_on_iface_down(fds, nfds);
	if (hup_count > 0) {
		LOG_DBG("poll offload iface-down hup_count=%d", hup_count);
		return hup_count;
	}

	if (immediate_ready || timeout == 0) {
		goto update_revents;
	}

	if (tracked_count > 0) {
		k_timeout_t poll_timeout = (timeout < 0) ? K_FOREVER : K_MSEC(timeout);
		int ret = k_poll(events, tracked_count, poll_timeout);

		if (ret != 0 && ret != -EAGAIN) {
			LOG_ERR("k_poll failed: %d", ret);
		}
	}

update_revents:
	ready_count = 0;
	for (int i = 0; i < nfds; i++) {
		struct erpc_wifi_socket *sock = find_socket_by_fd(fds[i].fd);

		if (sock) {
			k_spinlock_key_t key = k_spin_lock(&sock->state_lock);
			sock->waiting = false;
			uint32_t ev = (uint32_t)sock->triggered_events;

			if ((ev & SOCKET_EVENT_RX) && (fds[i].events & ZVFS_POLLIN)) {
				fds[i].revents |= ZVFS_POLLIN;
			}
			if ((ev & SOCKET_EVENT_TX) && (fds[i].events & ZVFS_POLLOUT)) {
				fds[i].revents |= ZVFS_POLLOUT;
			}
			if (ev & SOCKET_EVENT_ERR) {
				fds[i].revents |= ZVFS_POLLERR;
			}
			if (ev & SOCKET_EVENT_CLOSE) {
				fds[i].revents |= ZVFS_POLLHUP;
			}

			if (fds[i].revents != 0) {
				ready_count++;
			}
			k_spin_unlock(&sock->state_lock, key);
		}
	}

	LOG_INF("poll offload done ready_count=%d", ready_count);
	return ready_count;
}

static int erpc_wifi_socket_poll_update(struct erpc_wifi_socket *sock, struct zvfs_pollfd *pfd, struct k_poll_event **pev)
{
	if (!sock) {
		/* Not owned by this driver: ignore and let owner handle update path. */
		return 0;
	}

	k_spinlock_key_t key = k_spin_lock(&sock->state_lock);
	sock->waiting = false;

	if (*pev != NULL && (*pev)->type == K_POLL_TYPE_SIGNAL) {
		if ((*pev)->state == K_POLL_STATE_SIGNALED) {
			k_poll_signal_reset(&sock->poll_signal);
			uint32_t ev = (uint32_t)sock->triggered_events;

			if ((ev & SOCKET_EVENT_RX) && (pfd->events & ZVFS_POLLIN)) {
				pfd->revents |= ZVFS_POLLIN;
			}
			if ((ev & SOCKET_EVENT_TX) && (pfd->events & ZVFS_POLLOUT)) {
				pfd->revents |= ZVFS_POLLOUT;
			}
			if (ev & SOCKET_EVENT_ERR) {
				pfd->revents |= ZVFS_POLLERR;
			}
			if (ev & SOCKET_EVENT_CLOSE) {
				pfd->revents |= ZVFS_POLLHUP;
			}
		}
		(*pev)++;
	}
	k_spin_unlock(&sock->state_lock, key);

	return 0;
}

static int erpc_wifi_socket_ioctl(void *obj, unsigned int request, va_list args)
{
	struct erpc_wifi_socket *sock = obj;

	switch (request) {
#define ERPC_WIFI_SOL_SOCKET  0xfff
#define ERPC_WIFI_SO_NONBLOCK 0x2000

	case F_SETFL: {
		int new_flags = va_arg(args, int);
		int old_flags = sock->flags;
		
		if ((new_flags ^ old_flags) & O_NONBLOCK) {
			uint32_t val = (new_flags & O_NONBLOCK) ? 1U : 0U;
			bool ram_held = false;
			int __w = erpc_wifi_ensure_awake_tx(ERPC_PMGR_JOB_ID_SEND, &ram_held);
			if (__w != 0) {
				LOG_DBG("erpc_wifi_ensure_awake_tx failed: IN %s = %d", __func__, __w);
				if (ram_held) {
					erpc_wifi_pmgr_ram_release(ERPC_PMGR_JOB_ID_SEND);
				}
				erpc_wifi_ps_notify_wakeup();
				errno = -__w;
				return -1;
			}
			erpc_wifi_msg_socksetopt_t nb_msg = { .fd = sock->fd,
											  .level = ERPC_WIFI_SOL_SOCKET,
											  .optname = ERPC_WIFI_SO_NONBLOCK,
											  .optval = &val, .optlen = sizeof(val) };
			int rc = erpc_wifi_send_cmd(ERPC_WIFI_SOCKET_SETOPT_CMD, &nb_msg, sizeof(nb_msg), -1);
			if (ram_held) {
				erpc_wifi_pmgr_ram_release(ERPC_PMGR_JOB_ID_SEND);
			}
			erpc_wifi_ps_notify_wakeup();
			if (rc < 0) {
				errno = -rc;
				return -1;
			}
			LOG_DBG("Forwarded O_NONBLOCK to server for fd %d: val=%u", sock->fd, val);
		}
		sock->flags = new_flags;
		return 0;
	}
	case F_GETFL:
		LOG_DBG("Socket flags request: %d: 0x%x", request, sock->flags);
		return sock->flags;

	case ZFD_IOCTL_POLL_PREPARE: {
		struct zvfs_pollfd *pfd = va_arg(args, struct zvfs_pollfd *);
		struct k_poll_event **pev = va_arg(args, struct k_poll_event **);
		struct k_poll_event *pev_end = va_arg(args, struct k_poll_event *);

		// LOG_INF("POLL_PREPARE fd=%d events=0x%x", pfd->fd, pfd->events);

		if (*pev >= pev_end) {
			return -ENOSPC;
		}

		ensure_poll_task_started();

		k_spinlock_key_t key = k_spin_lock(&sock->state_lock);
		uint32_t cached = (uint32_t)sock->triggered_events;
		uint32_t requested_mask = 0;

		if (pfd->events & ZVFS_POLLIN) {
			requested_mask |= SOCKET_EVENT_RX;
		}
		if (pfd->events & ZVFS_POLLOUT) {
			requested_mask |= SOCKET_EVENT_TX;
		}
		if (pfd->events & ZVFS_POLLERR) {
			requested_mask |= SOCKET_EVENT_ERR;
		}
		if (pfd->events & ZVFS_POLLHUP) {
			requested_mask |= SOCKET_EVENT_CLOSE;
		}

		bool notify_connected = false;
		if (sock->connect_pending && (cached & SOCKET_EVENT_TX)) {
			sock->connect_pending = false;
			sock->connected = true;
			sock->socket_error = 0;
			notify_connected = true;
		}

		k_poll_signal_reset(&sock->poll_signal);
		sock->poll_events = pfd->events;
		sock->waiting = true;

		k_poll_event_init(*pev, K_POLL_TYPE_SIGNAL, K_POLL_MODE_NOTIFY_ONLY,
				  &sock->poll_signal);
		(*pev)++;

		uint32_t ready = sock->triggered_events & requested_mask;
		bool writable = (sock->type == SOCK_DGRAM) ||
				(sock->type == SOCK_STREAM && sock->connected && !sock->connect_pending && sock->socket_error == 0);

		bool do_signal = false;
		int sig_val = 0;

		if (ready != 0) {
			sock->waiting = false;
			do_signal = true;
			sig_val = (int)ready;
		} else if ((pfd->events & ZVFS_POLLOUT) && writable) {
			/* Synthetically report POLLOUT if writable */
			sock->triggered_events |= SOCKET_EVENT_TX;
			sock->waiting = false;
			do_signal = true;
			sig_val = SOCKET_EVENT_TX;
		} else {
			k_sem_give(&poll_task_sem);
		}
		k_spin_unlock(&sock->state_lock, key);

		if (notify_connected) {
			erpc_wifi_ps_notify_socket_connected();
		}

		if (do_signal) {
			k_poll_signal_raise(&sock->poll_signal, sig_val);
		}

		return 0;
	}

	case ZFD_IOCTL_POLL_OFFLOAD: {
		struct zvfs_pollfd *fds = va_arg(args, struct zvfs_pollfd *);
		int nfds = va_arg(args, int);
		int timeout = va_arg(args, int);

		return erpc_wifi_socket_poll_offload(fds, nfds, timeout);
	}

	case ZFD_IOCTL_POLL_UPDATE: {
		struct zvfs_pollfd *pfd = va_arg(args, struct zvfs_pollfd *);
		struct k_poll_event **pev = va_arg(args, struct k_poll_event **);

		int ret = erpc_wifi_socket_poll_update(sock, pfd, pev);
		// LOG_INF("POLL_UPDATE fd=%d events=0x%x revents=0x%x ret=%d", pfd->fd, pfd->events, pfd->revents, ret);
		return ret;
	}
#if 1
	case ZFD_IOCTL_SET_LOCK: {
		struct k_mutex *lock = va_arg(args, struct k_mutex *);
		sock->lock = lock;
		printk("SET_LOCK stored lock=%p zfd=%d remote=%d\n", (void *)lock, sock->zfd,
		       sock->fd);
		return 0;
	}
#endif
	default:
		errno = EINVAL;
		return -1;
	}
}

static int erpc_wifi_socket_getpeername(void *obj, struct sockaddr *addr, socklen_t *addrlen)
{
	struct erpc_wifi_socket *sock = (struct erpc_wifi_socket *)obj;

	if (sock == NULL || !sock->in_use) {
		errno = EBADF;
		return -1;
	}

	if (!sock->connected) {
		errno = ENOTCONN;
		return -1;
	}

	if (addr == NULL || addrlen == NULL) {
		errno = EINVAL;
		return -1;
	}

	if (sock->family == AF_INET) {
		if (*addrlen < sizeof(struct sockaddr_in)) {
			errno = EINVAL;
			return -1;
		}

		struct sockaddr_in *sin = (struct sockaddr_in *)addr;
		memset(sin, 0, sizeof(*sin));
		sin->sin_family = AF_INET;
		sin->sin_port = htons(sock->port);

		if (net_addr_pton(AF_INET, sock->addr_str, &sin->sin_addr) < 0) {
			errno = EINVAL;
			return -1;
		}

		*addrlen = sizeof(*sin);
	}
#if defined(CONFIG_NET_IPV6)
	else if (sock->family == AF_INET6) {
		if (*addrlen < sizeof(struct sockaddr_in6)) {
			errno = EINVAL;
			return -1;
		}

		struct sockaddr_in6 *sin6 = (struct sockaddr_in6 *)addr;
		memset(sin6, 0, sizeof(*sin6));
		sin6->sin6_family = AF_INET6;
		sin6->sin6_port = htons(sock->port);

		if (net_addr_pton(AF_INET6, sock->addr_str, &sin6->sin6_addr) < 0) {
			errno = EINVAL;
			return -1;
		}

		*addrlen = sizeof(*sin6);
	}
#endif
	else {
		errno = EAFNOSUPPORT;
		return -1;
	}

	return 0;
}

static int erpc_wifi_socket_getsockname(void *obj, struct sockaddr *addr, socklen_t *addrlen)
{
	struct erpc_wifi_socket *sock = (struct erpc_wifi_socket *)obj;

	if (sock == NULL || !sock->in_use) {
		errno = EBADF;
		return -1;
	}

	if (addr == NULL || addrlen == NULL) {
		errno = EINVAL;
		return -1;
	}

	if (sock->family == AF_INET) {
		if (*addrlen < sizeof(struct sockaddr_in)) {
			errno = EINVAL;
			return -1;
		}

		struct sockaddr_in *sin = (struct sockaddr_in *)addr;
		memset(sin, 0, sizeof(*sin));
		sin->sin_family = AF_INET;
		sin->sin_port = htons(sock->bound_port);
		sin->sin_addr.s_addr = INADDR_ANY;

		*addrlen = sizeof(*sin);
	}
#if defined(CONFIG_NET_IPV6)
	else if (sock->family == AF_INET6) {
		if (*addrlen < sizeof(struct sockaddr_in6)) {
			errno = EINVAL;
			return -1;
		}

		struct sockaddr_in6 *sin6 = (struct sockaddr_in6 *)addr;
		memset(sin6, 0, sizeof(*sin6));
		sin6->sin6_family = AF_INET6;
		sin6->sin6_port = htons(sock->bound_port);
		memset(&sin6->sin6_addr, 0, sizeof(struct in6_addr)); // IN6ADDR_ANY

		*addrlen = sizeof(*sin6);
	}
#endif
	else {
		errno = EAFNOSUPPORT;
		return -1;
	}

	return 0;
}

static const struct socket_op_vtable erpc_wifi_socket_fd_op_vtable = {
	.fd_vtable =
		{
			.read = erpc_wifi_socket_read,
			.write = erpc_wifi_socket_write,
			.close = erpc_wifi_socket_close,
			.ioctl = erpc_wifi_socket_ioctl,
		},

	.bind = erpc_wifi_socket_bind,
	.connect = erpc_wifi_socket_connect,
	.listen = erpc_wifi_socket_listen,
	.accept = erpc_wifi_socket_accept,
	.sendto = erpc_wifi_socket_sendto,
	.recvfrom = erpc_wifi_socket_recvfrom,
	.getsockopt = erpc_wifi_socket_getsockopt,
	.setsockopt = erpc_wifi_socket_setsockopt,
	.sendmsg = erpc_wifi_socket_sendmsg,
	.getpeername = erpc_wifi_socket_getpeername,
	.getsockname = erpc_wifi_socket_getsockname,

};

static int erpc_wifi_socket_create(int family, int type, int proto)
{
	bool ram_held = false;
	int __w = erpc_wifi_ensure_awake_tx(ERPC_PMGR_JOB_ID_SEND, &ram_held);
	if (__w != 0) { 
		LOG_INF("erpc_wifi_ensure_awake_tx failed: IN %s = %d", __func__,__w);
		if (ram_held) {
			(void)erpc_wifi_pmgr_ram_release(0);
		}
		errno = -__w;
		return -1;
	}

	int err;
	int sock;
	uint8_t family_erpc_wifi;
	int fd = zvfs_reserve_fd();
	struct erpc_wifi_socket *socket = NULL;

	if (fd < 0) {
		errno = ENFILE;
		if (ram_held) {
			erpc_wifi_pmgr_ram_release(0);
		}
		erpc_wifi_ps_notify_wakeup();
		return -1;
	}

	LOG_DBG("erpc_wifi_socket_create");
	LOG_DBG("family: %d", family);
	LOG_DBG("type: %d", type);
	LOG_DBG("proto: %d", proto);

	/* Map Zephyr socket.h family to RA RPC's */
	err = erpc_wifi_socket_family_from_posix(family, &family_erpc_wifi);
	if (err) {
		LOG_ERR("unsupported family: %d", family);
		zvfs_free_fd(fd);
		if (ram_held) {
			erpc_wifi_pmgr_ram_release(0);
		}
		erpc_wifi_ps_notify_wakeup();
		errno = -err;
		return -1;
	}
	erpc_wifi_msg_socket_create_t sc_msg = { .domain = family_erpc_wifi, .type = type, .protocol = proto };
	sock = erpc_wifi_send_cmd(ERPC_WIFI_SOCKET_CREATE_CMD, &sc_msg, sizeof(sc_msg), -1);
	if (ram_held) {
		erpc_wifi_pmgr_ram_release(0);
	}
	erpc_wifi_ps_notify_wakeup();
	LOG_DBG("ra6w1_socket: %d", sock);

	if (sock < 0) {
		zvfs_free_fd(fd);
		errno = -sock;
		return -1;
	}

	socket = erpc_wifi_socket_allocate(sock, fd);

	if (socket == NULL) {
		bool ram_held2 = false;
		(void)erpc_wifi_ensure_awake_tx(ERPC_PMGR_JOB_ID_SEND, &ram_held2);
		(void)erpc_wifi_send_cmd(ERPC_WIFI_SOCKET_CLOSE_CMD, &sock, sizeof(sock), -1);
		if (ram_held2) {
			erpc_wifi_pmgr_ram_release(ERPC_PMGR_JOB_ID_SEND);
		}
		erpc_wifi_ps_notify_wakeup();
		zvfs_free_fd(fd);
		errno = ENFILE;
		return -1;
	}
	
	socket->family = family;
	socket->type = type;
	socket->protocol = proto;

	if (type == SOCK_DGRAM) {
		LOG_INF("UDP socket created");
	}

	zvfs_finalize_typed_fd(fd, socket,
			       (const struct fd_op_vtable *)&erpc_wifi_socket_fd_op_vtable,
			       ZVFS_MODE_IFSOCK);

	return fd;
}

static bool erpc_wifi_socket_is_supported(int family, int type, int proto)
{
	if (family == AF_INET) {
		if (type == SOCK_STREAM && proto == IPPROTO_TCP) {
			return true;
		}

		if (type == SOCK_DGRAM && proto == IPPROTO_UDP) {
			return true;
		}

		if (type == SOCK_RAW && proto == IPPROTO_ICMP) {
			return true;
		}

		return false;
	}

	if (family == AF_INET6) {
		if (type == SOCK_STREAM && proto == IPPROTO_TCP) {
			return true;
		}

		if (type == SOCK_DGRAM && proto == IPPROTO_UDP) {
			return true;
		}

		if (type == SOCK_RAW && proto == IPPROTO_ICMPV6) {
			return true;
		}

		return false;
	}

	return false;
}

void erpc_wifi_offload_srdy_callback(void)
{
	/*
	 * If the host explicitly pulsed WAKE for a TX operation, this rising
	 * edge belongs to that host wake handshake (RA reports TIM:FAST).
	 * erpc_wifi_ensure_awake_tx() is polling the physical level directly,
	 * so the autonomous socket poll task must not consume this edge.
	 */
	if (atomic_get(&g_host_wake_inflight) != 0) {
		return;
	}

	/*
	 * During host eRPC this may be the normal response SRDY,
	 * but it may also overlap a real incoming socket event.
	 * Defer classification instead of dropping the edge.
	 * Do not defer responses generated by GET_SOCKET_EVT or GET_SERVER_EVT itself,
	 * otherwise the poll task can self-trigger forever.
	 */
	if (atomic_get(&g_host_erpc_inflight) != 0) {
		if (atomic_get(&g_socket_evt_query_inflight) == 0 &&
		    atomic_get(&g_server_evt_query_inflight) == 0) {
			atomic_set(&g_srdy_deferred, 1);
		}
		return;
	}

	atomic_set(&g_srdy_irq_pending, 1);

	/* Wake up the poll task immediately on SRDY interrupt */
	extern struct k_sem poll_task_sem;
	k_sem_give(&poll_task_sem);
}

void erpc_wifi_offload_clear_srdy_pending(void)
{
	atomic_set(&g_srdy_irq_pending, 0);
	atomic_set(&g_srdy_deferred, 0);

}

extern void erpc_wifi_dns_offload_init(void);

int erpc_wifi_socket_offload_init(struct net_if *iface)
{
	memset(sockets, 0, sizeof(sockets));
	k_sem_init(&poll_task_sem, 0, 1);

	k_work_init_delayable(&g_srdy_deferred_work, erpc_wifi_srdy_deferred_work);

	erpc_transport_register_srdy_cb(erpc_wifi_offload_srdy_callback);

	net_if_socket_offload_set(iface, erpc_wifi_socket_create);

	net_iface = iface;

#ifndef CONFIG_DNS_RESOLVER
	erpc_wifi_dns_offload_init();
#endif

	return 0;
}

#ifdef CONFIG_NET_SOCKETS_OFFLOAD
NET_SOCKET_OFFLOAD_REGISTER(erpc_wifi, CONFIG_NET_SOCKETS_OFFLOAD_PRIORITY, AF_UNSPEC,
			    erpc_wifi_socket_is_supported, erpc_wifi_socket_create);
#endif